import { Command } from "commander";
import { resolve, basename } from "node:path";
import { existsSync, writeFileSync, mkdirSync, readFileSync } from "node:fs";
import { createInterface } from "node:readline";
import { execSync } from "node:child_process";
import chalk from "chalk";
import { writeProjectConfig, findProjectConfig } from "../lib/config.js";
import { createApiClient, ApiError } from "../lib/api-client.js";
import { getApiKey, saveApiKey } from "../lib/credentials.js";
import { success, error, info, keyValue, warn } from "../lib/output.js";

function generateAgentMd(slug: string, apiUrl: string): string {
  return `# Remb — AI Context Management

> This file was generated by \`remb init\`. It documents the Remb CLI so your AI coding assistant knows how to use it.

## Project

- **Slug**: \`${slug}\`
- **API**: \`${apiUrl}\`
- **Config**: \`.remb.yml\` (committed, no secrets)

## What is Remb?

Remb is a persistent memory and context layer for AI coding sessions. It lets you save, retrieve, and scan project context — features, architecture decisions, code patterns — so AI assistants have deep project knowledge across sessions.

## Authentication

The user must be logged in before any command works (except \`init\`).

\`\`\`sh
remb login              # Opens browser OAuth flow
remb login --key <key>  # Direct API key auth
remb whoami             # Check current identity
remb logout             # Clear credentials
\`\`\`

Credentials are stored in \`~/.config/remb/credentials.json\` (never in the repo).

## Commands Reference

### remb init
Initialize a project — creates local config, generates this AI reference doc, and registers the project on the Remb server (if logged in).

\`\`\`sh
remb init                      # Init with directory name as project slug
remb init my-app               # Init with specific name
remb init --force              # Re-initialize (overwrites config + REMB.md)
\`\`\`

**What it does**:
1. Creates \`.remb.yml\` (project config)
2. Generates \`REMB.md\` (this file — AI agent reference)
3. Auto-detects git remote URL, repo name, and branch
4. Registers the project on the Remb server (if authenticated)

If not logged in, run \`remb login\` first, then \`remb init --force\` to register.

### remb push
Trigger a cloud scan to update project context after pushing code. Shows live progress with percentage and per-file status in the terminal.

\`\`\`sh
remb push                      # Scan current project (with live progress)
remb push -p <slug>            # Scan specific project
remb push --force              # Skip git pre-flight checks
remb push --no-progress        # Fire and forget (don't wait for results)
\`\`\`

**Pre-flight checks**: Verifies you're in a git repo, warns about uncommitted changes, checks if local is ahead of remote.

**Live progress**: After triggering, polls for scan status and displays a progress bar. During high load, scans queue; the status will show \`queued\` before it turns \`running\`. The CLI waits and shows progress regardless.

**Returns**: \`started\` | \`already_running\` | \`up_to_date\` | \`queued\`

### remb scan
**Local scan** — reads files directly from disk in the CLI process, groups them by directory into context entries, and uploads the results to Remb. No git required, no GitHub access needed. Works offline repos, monorepos, and any directory structure.

> **Local vs cloud**: \`remb scan\` runs entirely on your machine and uploads results immediately. \`remb push\` triggers a server-side scan that reads from GitHub — it requires committed + pushed changes and a connected GitHub repo.

\`\`\`sh
remb scan                           # Scan current directory (all subdirs)
remb scan --path src/               # Scan a specific subdirectory
remb scan -p <slug> --path src/     # Scan with explicit project slug
remb scan --depth 3                 # Limit recursion depth (default: 5)
remb scan --dry-run                 # Preview features without saving
remb scan --ignore "tests,dist"     # Skip directories by name
\`\`\`

**What it does**:
1. Walks the target directory (respecting \`--depth\` and \`--ignore\`)
2. Groups source files by directory — each directory becomes one context entry (feature)
3. Shows a preview: feature name, detected tags, content size in KB
4. Uploads all entries via \`saveBatch\` with a progress counter

**Preview output** (before saving):
\`\`\`
Found 84 source files across 12 directories.

  ● app/api — typescript, backend — 4.2KB
  ● components/dashboard — typescript, react — 11.8KB
  ● lib — typescript, utilities — 6.1KB
  ...

Saving context entries... 8/12
✓ Uploaded 12 context entries to my-app
\`\`\`

**When to use \`remb scan\` vs \`remb push\`**:
| Scenario | Use |
|---|---|
| No git remote / not on GitHub | \`remb scan\` |
| First-time setup, no commits yet | \`remb scan\` |
| Monorepo with multiple sub-projects | \`remb scan --path packages/my-pkg\` |
| After pushing commits to GitHub | \`remb push\` |
| Want AI-powered per-file analysis | \`remb push\` |

### remb save
Save a context entry for a feature.

\`\`\`sh
remb save -f "auth-flow" -c "Uses NextAuth with GitHub OAuth..."
remb save -f "db-schema" -c "PostgreSQL via Supabase with RLS..." -t "database,security"
remb save -f "api-design" --type architecture -c "REST API with..."
\`\`\`

**Options**: \`-f/--feature\` (required), \`-c/--content\` (required), \`-p/--project\`, \`-t/--tags\`, \`--type\`

### remb get
Retrieve saved context entries.

\`\`\`sh
remb get                           # All entries for project
remb get -f "auth-flow"            # Entries for specific feature
remb get -l 10 --format json       # Limit and format output
remb get --format markdown         # Markdown output
\`\`\`

**Formats**: \`table\` (default), \`json\`, \`markdown\`

### remb context
Download the full project context bundle as a single markdown document.

\`\`\`sh
remb context                       # Print to stdout
remb context -o context.md         # Write to file
remb context --json                # JSON format
\`\`\`

This is ideal for feeding full project knowledge into an AI assistant.

### remb diff
Analyze uncommitted git changes and save as context.

\`\`\`sh
remb diff                          # Unstaged changes
remb diff --staged                 # Staged changes only
remb diff --all                    # All changes (staged + unstaged)
\`\`\`

### remb memory
Manage persistent AI memories. Memories have two scopes:
- **Project-scoped** — linked to a specific project (relevant to that codebase only)
- **Global** — no project scope (project_id is null) — apply across ALL projects

\`\`\`sh
remb memory add -t "Title" -c "Content..." --tier core --category architecture
remb memory add -t "Title" -c "Content..." --project my-app  # project-scoped memory
remb memory list                       # All memories (shows [project] or [global] badge)
remb memory list --project my-app      # Project memories + global memories
remb memory list --global              # Only global memories
remb memory list --tier core -s "auth" # Search core-tier memories
remb memory update <id> -c "Updated content..."
remb memory delete <id>
remb memory promote <id> --to core     # Promote to core tier
\`\`\`

**Tiers**: \`core\` (always loaded), \`active\` (session-relevant), \`archive\` (historical)

### remb link
Create dependency relationships between features.

\`\`\`sh
remb link --from "auth-flow" --to "user-profile" --type depends_on
\`\`\`

**Types**: \`depends_on\`, \`extends\`, \`uses\`

### remb projects
List and manage projects. Switch the active project for the current workspace.

\`\`\`sh
remb projects list                           # List all projects
remb projects list --status active           # Filter by status
remb projects list --format json             # JSON output
remb projects use my-app                     # Set active project (writes .remb.yml)
remb projects switch my-app                  # Same as use
\`\`\`

**remb projects use <slug>** looks up the project on the server, confirms it exists, then writes \`.remb.yml\` in the current directory. All subsequent commands will use the new project.

### remb serve
Start a local MCP server for direct AI tool integration (stdio transport).

\`\`\`sh
remb serve                         # Serve current project
remb serve --project <slug>        # Serve specific project
\`\`\`

**Exposed MCP tools**:

Context & scanning:
- \`save_context\` — persist knowledge about a feature
- \`get_context\` — recall entries (with optional feature filter)
- \`load_project_context\` — full project bundle as markdown
- \`analyze_diff\` — AI-analyze uncommitted git changes

Memory management:
- \`memory_list\` — list memories; pass \`projectSlug\` to get project + global memories
- \`memory_create\` — create a memory (omit \`projectSlug\` for global scope)
- \`memory_update\` — update title, content, tier, category, or tags
- \`memory_delete\` — delete a memory by ID
- \`memory_promote\` — change a memory's tier

Conversation tracking:
- \`conversation_log\` — record what was discussed/accomplished (call after completing work)
- \`conversation_history\` — load prior session history (call at session start)

### remb history
View conversation history — see what AI discussed and did across sessions.

\`\`\`sh
remb history                           # Last 20 entries as timeline
remb history --date 2025-03-15         # Single day
remb history --from 2025-03-01 --to 2025-03-15  # Date range
remb history --limit 50                # More entries
remb history --format markdown         # Markdown output
remb history --format json             # Raw JSON
remb history -p <slug>                 # Filter by project
\`\`\`

**MCP tools** (available when connected via \`remb serve\` or the hosted MCP endpoint):
- \`conversation_log\` — record what you discussed or accomplished (call after completing work)
- \`conversation_history\` — load recent conversation history (call at session start to catch up)

## Step-by-Step Workflows

Follow these workflows in order. Each numbered step must complete before proceeding to the next.

### 1. First-time project setup

1. **Authenticate** — \`remb login\` (opens browser OAuth or use \`--key <key>\`)
2. **Initialize** — \`remb init\` (creates \`.remb.yml\`, generates \`REMB.md\`, registers project on server)
3. **First scan** — \`remb push\` (triggers cloud scan, shows live progress until complete)
4. **Verify** — \`remb projects list\` (confirm project appears with \`active\` status)

### 2. Update context after code changes

1. **Commit & push** — \`git add . && git commit -m "feat: ..." && git push\`
2. **Trigger scan** — \`remb push\` (detects new commits, runs cloud scan with progress)
3. **Wait for completion** — the CLI shows a progress bar; wait for \`Scan complete\` message

### 3. Save knowledge manually

1. **Save a feature** — \`remb save -f "feature-name" -c "Description..."\`
2. **Verify** — \`remb get -f "feature-name"\` (confirm entry was stored)

### 4. Load full context into AI session

1. **Bundle context** — \`remb context -o CONTEXT.md\`
2. **Feed to AI** — provide the generated \`CONTEXT.md\` file to your AI assistant

### 5. Analyze local changes before committing

1. **Make edits** — modify source files as needed
2. **Diff analysis** — \`remb diff --all\` (analyzes all staged + unstaged changes)
3. **Review** — check the generated context entries summarizing your changes

### 6. Local scan (no git / no GitHub required)

Use this when the repo isn't on GitHub, has no git remote, or you want to scan a specific subdirectory.

1. **Preview first** — \`remb scan --dry-run\` (see what directories will be scanned, no upload)
2. **Full scan** — \`remb scan\` (uploads all directory-grouped context entries)
3. **Verify** — \`remb get\` (confirm entries appear in the project)
4. **Targeted scan** — \`remb scan --path src/ --depth 3\` to narrow the scope

## MCP Integration

Add Remb as an MCP server in your IDE for direct AI tool access:

**Cursor / VS Code** (\`.cursor/mcp.json\` or \`.vscode/mcp.json\`):
\`\`\`json
{
  "mcpServers": {
    "remb": {
      "command": "remb",
      "args": ["serve"]
    }
  }
}
\`\`\`

Or connect to the hosted endpoint at \`${apiUrl}/api/mcp\` for aggregated MCP access with all your connected servers.

## Exit Codes

- \`0\` — Success
- \`1\` — Error (auth failure, network error, validation error)

All commands respect the \`-p/--project <slug>\` flag or fall back to \`.remb.yml\` in the current directory tree.
`;
}

export const initCommand = new Command("init")
  .description("Initialize a project with remb tracking")
  .argument("[project-name]", "Project name (defaults to directory name)")
  .option("--api-url <url>", "API server URL", "https://www.useremb.com")
  .option("--force", "Overwrite existing configuration", false)
  .option(
    "--ide <ide>",
    "IDE to configure (vscode, cursor, windsurf, cline, jetbrains, claude, aider, all)",
  )
  .action(async (projectName: string | undefined, opts) => {
    const cwd = process.cwd();
    const name = projectName ?? basename(cwd);

    // Generate a slug
    const slug = name
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-|-$/g, "");

    if (!slug) {
      error("Invalid project name — must contain at least one alphanumeric character.");
      process.exit(1);
    }

    // Check for existing config
    const existing = findProjectConfig(cwd);
    if (existing && !opts.force) {
      warn(`Already initialized at ${chalk.dim(existing.dir + "/.remb.yml")}`);
      info(`Use ${chalk.bold("--force")} to overwrite.`);
      return;
    }

    // Determine IDE: flag > existing config > interactive prompt > auto-detect
    const ide = await resolveIde(opts.ide, existing?.config.ide);

    const filePath = writeProjectConfig(cwd, {
      project: slug,
      api_url: opts.apiUrl,
      ide,
    });

    // Generate AI agent reference doc
    const agentMdPath = resolve(cwd, "REMB.md");
    writeFileSync(agentMdPath, generateAgentMd(slug, opts.apiUrl), "utf-8");

    console.log();
    success(`Project ${chalk.bold(slug)} initialized!`);
    keyValue("Config", filePath);
    keyValue("Agent docs", agentMdPath);
    keyValue("Project", slug);
    keyValue("API URL", opts.apiUrl);
    keyValue("IDE", ide);
    console.log();

    // Auto-register project on server if logged in (or offer to sign in)
    let apiKey = getApiKey();
    if (!apiKey && process.stdout.isTTY) {
      console.log(
        chalk.dim("  You're not signed in — signing in lets Remb register your project and sync context.")
      );
      const shouldLogin = await promptYesNo("  Sign in now?");
      if (shouldLogin) {
        apiKey = await runInlineLogin(opts.apiUrl);
      }
    }

    if (apiKey) {
      try {
        // Auto-detect git info
        let repoUrl: string | undefined;
        let repoName: string | undefined;
        let branch: string | undefined;
        try {
          repoUrl = execSync("git remote get-url origin", { cwd, encoding: "utf-8" }).trim();
          const match = repoUrl.match(/[/:]([-\w.]+\/[-\w.]+?)(?:\.git)?$/);
          if (match) repoName = match[1];
          branch = execSync("git rev-parse --abbrev-ref HEAD", { cwd, encoding: "utf-8" }).trim();
        } catch {
          // Not a git repo or no remote — fine
        }

        const client = createApiClient({ apiUrl: opts.apiUrl, apiKey });
        const { project } = await client.createProject({
          name: slug,
          repoUrl,
          repoName,
          branch,
        });
        success(`Project registered on Remb ${chalk.dim(`(${project.slug})`)}`);
      } catch (err) {
        if (err instanceof ApiError && err.statusCode === 409) {
          info(`Project ${chalk.bold(slug)} already exists on server — linked.`);
        } else {
          warn(`Could not register project on server: ${err instanceof Error ? err.message : "unknown error"}`);
          info(`You can register it later from the dashboard.`);
        }
      }
    } else if (!getApiKey()) {
      info(`Run ${chalk.bold("remb login")} to register this project on the server.`);
    }

    // Check for .gitignore and suggest adding credentials
    const gitignorePath = resolve(cwd, ".gitignore");
    if (existsSync(gitignorePath)) {
      info(
        `${chalk.dim("Tip:")} .remb.yml and REMB.md are safe to commit — they contain no secrets.`
      );
    }

    // Inject into IDE-specific instruction folders
    const injected = injectIntoIDEContextFiles(cwd, slug, opts.apiUrl, ide);
    if (injected.length > 0) {
      info(`AI context injected into: ${injected.map((p) => chalk.dim(p)).join(", ")}`);
    }

    info(
      `${chalk.bold("REMB.md")} generated — your IDE's AI agent can read it to learn all Remb commands.`
    );
  });

function injectIntoIDEContextFiles(cwd: string, slug: string, apiUrl: string, ide: string): string[] {
  const START_MARKER = "<!-- remb:start -->";
  const END_MARKER = "<!-- remb:end -->";

  const all = ide === "all";
  const is = (name: string) => all || ide === name;

  type Target = {
    path: string;
    label: string;
    content: string;
    enabled: boolean;
    fileHeader?: string; // static content prepended before the remb block (e.g. YAML frontmatter)
  };

  const targets: Target[] = [
    {
      path: resolve(cwd, ".github", "copilot-instructions.md"),
      label: ".github/copilot-instructions.md",
      content: generateCopilotInstructions(slug, apiUrl),
      enabled: is("vscode"),
    },
    {
      path: resolve(cwd, ".cursor", "rules", "remb.mdc"),
      label: ".cursor/rules/remb.mdc",
      content: generateCursorRules(slug, apiUrl),
      enabled: is("cursor"),
    },
    {
      path: resolve(cwd, ".windsurfrules"),
      label: ".windsurfrules",
      content: generateWindsurfRules(slug, apiUrl),
      enabled: is("windsurf"),
    },
    {
      path: resolve(cwd, ".clinerules"),
      label: ".clinerules",
      content: generateClineRules(slug, apiUrl),
      enabled: is("cline"),
    },
    {
      path: resolve(cwd, ".junie", "guidelines.md"),
      label: ".junie/guidelines.md",
      content: generateJetBrainsPrompt(slug, apiUrl),
      enabled: is("jetbrains"),
    },
    {
      path: resolve(cwd, "CLAUDE.md"),
      label: "CLAUDE.md",
      content: generateClaudeMd(slug, apiUrl),
      enabled: is("claude"),
    },
    {
      path: resolve(cwd, ".aider.conf.yml"),
      label: ".aider.conf.yml",
      content: generateAiderConfig(slug, apiUrl),
      enabled: is("aider"),
    },
    {
      path: resolve(cwd, ".github", "instructions", "remb-session.instructions.md"),
      label: ".github/instructions/remb-session.instructions.md",
      content: generateInstructionsMd(slug, apiUrl),
      enabled: is("vscode"),
      fileHeader: "---\napplyTo: '**'\n---",
    },
  ];

  const injected: string[] = [];

  for (const target of targets) {
    if (!target.enabled) continue;

    try {
      const dir = resolve(target.path, "..");
      if (!existsSync(dir)) {
        mkdirSync(dir, { recursive: true });
      }

      const block = `${START_MARKER}\n${target.content}\n${END_MARKER}`;
      const header = target.fileHeader ? target.fileHeader + "\n\n" : "";

      if (existsSync(target.path)) {
        const existing = readFileSync(target.path, "utf-8");
        const startIdx = existing.indexOf(START_MARKER);
        const endIdx = existing.indexOf(END_MARKER);
        if (startIdx !== -1 && endIdx !== -1) {
          // Markers found — surgically replace only the remb block
          const updated =
            existing.slice(0, startIdx) +
            block +
            existing.slice(endIdx + END_MARKER.length);
          writeFileSync(target.path, updated);
        } else if (target.fileHeader) {
          // File exists but unmanaged (no markers) — adopt it: write header + block
          writeFileSync(target.path, header + block + "\n");
        } else {
          // Append block after existing content
          writeFileSync(target.path, existing.trimEnd() + "\n\n" + block + "\n");
        }
      } else {
        writeFileSync(target.path, header + block + "\n");
      }

      injected.push(target.label);
    } catch {
      // Silently skip files we can't write
    }
  }

  // Auto-generate MCP config files
  const mcpConfig = JSON.stringify({
    mcpServers: {
      remb: { command: "remb", args: ["serve"] },
    },
  }, null, 2);

  if (is("vscode")) {
    const vscMcp = resolve(cwd, ".vscode", "mcp.json");
    if (!existsSync(vscMcp)) {
      try {
        mkdirSync(resolve(cwd, ".vscode"), { recursive: true });
        writeFileSync(vscMcp, mcpConfig + "\n");
        injected.push(".vscode/mcp.json");
      } catch { /* skip */ }
    }
  }

  if (is("cursor")) {
    const cursorMcp = resolve(cwd, ".cursor", "mcp.json");
    if (!existsSync(cursorMcp)) {
      try {
        mkdirSync(resolve(cwd, ".cursor"), { recursive: true });
        writeFileSync(cursorMcp, mcpConfig + "\n");
        injected.push(".cursor/mcp.json");
      } catch { /* skip */ }
    }
  }

  return injected;
}

// ─── Inline Login ─────────────────────────────────────────────────────────────

async function promptYesNo(message: string): Promise<boolean> {
  const rl = createInterface({ input: process.stdin, output: process.stdout });
  return new Promise((resolve) => {
    rl.question(`${message} ${chalk.dim("[Y/n]")}: `, (answer) => {
      rl.close();
      const a = answer.trim().toLowerCase();
      resolve(a === "" || a === "y" || a === "yes");
    });
  });
}

/** Open a URL in the user's default browser. */
async function openBrowser(url: string): Promise<void> {
  const { exec } = await import("node:child_process");
  const { platform } = await import("node:os");
  const os = platform();
  const cmd =
    os === "darwin" ? "open" :
    os === "win32" ? "start" :
    "xdg-open";
  exec(`${cmd} ${JSON.stringify(url)}`);
}

/** Run browser OAuth inline and return the API key, or null on failure. */
async function runInlineLogin(apiUrl: string): Promise<string | null> {
  const baseUrl = apiUrl.replace(/\/+$/, "");
  try {
    const res = await fetch(`${baseUrl}/api/cli/auth/start`, { method: "POST" });
    if (!res.ok) {
      warn("Could not start login flow.");
      return null;
    }

    const { state, authUrl } = await res.json() as { state: string; authUrl: string };

    console.log();
    info("Opening browser to authenticate...");
    console.log(chalk.dim(`  If the browser doesn't open, visit:`));
    console.log(chalk.dim(`  ${authUrl}`));

    await openBrowser(authUrl);

    const ora = (await import("ora")).default;
    const spinner = ora("Waiting for browser authentication...").start();

    const deadline = Date.now() + 120_000;
    while (Date.now() < deadline) {
      await new Promise((r) => setTimeout(r, 2_000));
      try {
        const poll = await fetch(`${baseUrl}/api/cli/auth/poll?state=${encodeURIComponent(state)}`);
        if (!poll.ok) continue;
        const data = await poll.json() as { status: string; apiKey?: string; login?: string };
        if (data.status === "completed" && data.apiKey) {
          spinner.stop();
          const path = saveApiKey(data.apiKey);
          console.log();
          success(`Authenticated${data.login ? ` as ${chalk.bold(data.login)}` : ""}!`);
          keyValue("Credentials", path);
          console.log();
          return data.apiKey;
        }
        if (data.status === "expired") break;
      } catch { /* retry */ }
    }

    spinner.fail("Login timed out.");
    return null;
  } catch {
    warn("Login failed — you can run `remb login` separately.");
    return null;
  }
}

// ─── IDE Resolution ───────────────────────────────────────────────────────────

const VALID_IDES = ["vscode", "cursor", "windsurf", "cline", "jetbrains", "claude", "aider", "all"] as const;
type IDE = typeof VALID_IDES[number];

const IDE_LABELS: Record<IDE, string> = {
  vscode:    "VS Code (GitHub Copilot)",
  cursor:    "Cursor",
  windsurf:  "Windsurf",
  cline:     "Cline",
  jetbrains: "JetBrains AI",
  claude:    "Claude Code",
  aider:     "Aider",
  all:       "All / Multiple IDEs",
};

/** Try to detect the IDE from environment variables and running processes. */
function detectIde(): string | null {
  const env = process.env;

  // VS Code sets TERM_PROGRAM=vscode in its integrated terminal
  if (env.TERM_PROGRAM === "vscode" || env.VSCODE_PID) return "vscode";

  // Cursor sets TERM_PROGRAM=cursor (it's an Electron fork of VS Code)
  if (env.TERM_PROGRAM === "cursor") return "cursor";

  // Windsurf sets TERM_PROGRAM=Windsurf
  if (env.TERM_PROGRAM?.toLowerCase() === "windsurf") return "windsurf";

  // JetBrains IDEs set TERMINAL_EMULATOR=JetBrains-JediTerm
  if (env.TERMINAL_EMULATOR?.includes("JetBrains")) return "jetbrains";

  // Claude Code typically runs via `claude` CLI — check parent command name
  if (env.CLAUDE_CODE === "1" || env.TERM_PROGRAM === "claude") return "claude";

  return null;
}

async function resolveIde(flagValue: string | undefined, configValue: string | undefined): Promise<string> {
  if (flagValue) {
    const normalized = flagValue.toLowerCase();
    if (!(VALID_IDES as readonly string[]).includes(normalized)) {
      warn(`Unknown IDE "${flagValue}". Valid options: ${VALID_IDES.join(", ")}`);
      warn("Falling back to: all");
      return "all";
    }
    return normalized;
  }

  if (configValue && (VALID_IDES as readonly string[]).includes(configValue)) {
    return configValue;
  }

  // Try auto-detection from environment
  const detected = detectIde();
  if (detected) {
    info(`Detected IDE: ${chalk.bold(IDE_LABELS[detected as IDE])}`);
    return detected;
  }

  // Interactive prompt when running in a real terminal
  if (process.stdout.isTTY) {
    return promptIde();
  }

  return "all";
}

async function promptIde(): Promise<string> {
  const rl = createInterface({ input: process.stdin, output: process.stdout });
  const choices = VALID_IDES.map((v, i) => ({ key: String(i + 1), value: v, label: IDE_LABELS[v] }));

  console.log();
  console.log(chalk.bold("  Which IDE are you using?"));
  console.log();
  for (const c of choices) {
    console.log(`    ${chalk.dim(c.key + ".")} ${c.label}`);
  }
  console.log();

  return new Promise((resolve) => {
    rl.question(chalk.bold("  Enter number: "), (answer) => {
      rl.close();
      const found = choices.find((c) => c.key === answer.trim());
      if (!found) {
        console.log(chalk.dim("  No selection — using: all"));
        resolve("all");
      } else {
        console.log(chalk.dim(`  Selected: ${found.label}`));
        resolve(found.value);
      }
    });
  });
}

// ─── IDE-Specific Generators ─────────────────────────────────────────────────

function mcpToolReference(): string {
  return `### Available MCP Tools

**Memory Management:**
- \`remb__memory_list\` — list memories (filter by tier, category, search)
- \`remb__memory_search\` — semantic search across all memories
- \`remb__memory_load_context\` — load all core + active memories as context
- \`remb__memory_create\` — create a new memory
- \`remb__memory_update\` — update an existing memory
- \`remb__memory_delete\` — delete a memory
- \`remb__memory_promote\` — promote a memory to a higher tier
- \`remb__memory_stats\` — get memory usage statistics
- \`remb__memory_image_upload\` — upload an image to memory
- \`remb__memory_image_list\` — list stored images

**Conversation Tracking:**
- \`remb__conversation_log\` — record what you discussed or accomplished
- \`remb__conversation_history\` — load recent conversation history

**Project & Context:**
- \`remb__projects_list\` — list all projects with feature counts
- \`remb__project_get\` — get project details, features, and latest scan
- \`remb__context_save\` — save a context entry for a feature
- \`remb__context_get\` — retrieve context entries (optional feature filter)
- \`remb__context_bundle\` — full project context as markdown

**Scanning & Analysis:**
- \`remb__scan_trigger\` — trigger a cloud scan
- \`remb__scan_status\` — check scan progress
- \`remb__diff_analyze\` — analyze a git diff and save extracted changes

**Cross-Project:**
- \`remb__cross_project_search\` — search across ALL projects for features, context, and memories
- \`remb__context_bundle\` — also works with other project slugs to load another project's full context
- \`remb__memory_create\` — create with no project_id to save global preferences that apply everywhere`;
}

function generateCopilotInstructions(slug: string, apiUrl: string): string {
  return `# Remb — AI Context Management Rules

## Project: \`${slug}\`
## API: \`${apiUrl}\`

## MANDATORY — Conversation Tracking

You MUST follow these rules in EVERY session:

1. **Session Start**: Call \`remb__conversation_history\` to load recent history and catch up on prior work.
2. **Load Context**: Call \`remb__memory_load_context\` to load all persistent project memories.
3. **During Work**: Call \`remb__conversation_log\` after completing significant work to record what was done.
4. **Session End**: Call \`remb__conversation_log\` with a summary before the conversation ends.
5. **Save Discoveries**: When you discover important architectural patterns, decisions, or gotchas, call \`remb__memory_create\` to save them.

These calls ensure context persists across sessions. Skipping them causes knowledge loss.

${mcpToolReference()}

## When to Use Each Tool

- **Starting a session** → \`conversation_history\` + \`memory_load_context\`
- **Need project info** → \`project_get\` or \`context_bundle\`
- **Saving knowledge** → \`context_save\` (feature-specific) or \`memory_create\` (cross-cutting)
- **After code changes** → \`scan_trigger\` to refresh, \`diff_analyze\` for targeted analysis
- **Finishing work** → \`conversation_log\` with summary of what was accomplished

## Cross-Project Referencing

When the user says "do it like I did in project X" or references another project:

1. Call \`remb__projects_list\` to find available projects
2. Call \`remb__cross_project_search\` with the concept to find matching patterns across all projects
3. Call \`remb__context_bundle\` with the other project's slug to load its full context
4. Apply the patterns from that project to the current work

**Global preferences** — memories created without a project_id apply to ALL projects. Use \`remb__memory_create\` with category \"preference\" and no project_id to save cross-project coding standards.`;
}

function generateCursorRules(slug: string, apiUrl: string): string {
  return `---
description: Remb context management — mandatory rules for AI sessions
globs: "**"
alwaysApply: true
---

# Remb — AI Context Management

**Project**: \`${slug}\` | **API**: \`${apiUrl}\`

## MANDATORY Rules

1. At session start, call \`remb__conversation_history\` and \`remb__memory_load_context\`.
2. After completing significant work, call \`remb__conversation_log\` to record it.
3. Before ending the session, call \`remb__conversation_log\` with a final summary.
4. Save important discoveries with \`remb__memory_create\`.

${mcpToolReference()}

## Usage Patterns

| Situation | Tool |
|---|---|
| Starting a session | \`conversation_history\` + \`memory_load_context\` |
| Need project info | \`project_get\` or \`context_bundle\` |
| Saving knowledge | \`context_save\` or \`memory_create\` |
| After code changes | \`scan_trigger\` or \`diff_analyze\` |
| Finishing work | \`conversation_log\` |
| Reference another project | \`cross_project_search\` + \`context_bundle\` |`;
}

function generateWindsurfRules(slug: string, apiUrl: string): string {
  return `# Remb — AI Context Management

Project: ${slug} | API: ${apiUrl}

## MANDATORY — Follow These Every Session

1. Session start → call \`remb__conversation_history\` and \`remb__memory_load_context\`
2. After significant work → call \`remb__conversation_log\`
3. Before ending → call \`remb__conversation_log\` with summary
4. Discoveries → call \`remb__memory_create\`

${mcpToolReference()}

## Quick Reference

- Starting: conversation_history + memory_load_context
- Project info: project_get or context_bundle
- Save knowledge: context_save (feature) or memory_create (general)
- After changes: scan_trigger or diff_analyze
- Finishing: conversation_log
- Reference another project: cross_project_search + context_bundle`;
}

function generateClineRules(slug: string, apiUrl: string): string {
  return `# Remb — AI Context Management

Project: ${slug} | API: ${apiUrl}

## MANDATORY Rules

These rules MUST be followed in every session:

1. ALWAYS call \`remb__conversation_history\` at session start to load prior context.
2. ALWAYS call \`remb__memory_load_context\` at session start to load project memories.
3. ALWAYS call \`remb__conversation_log\` after completing significant work.
4. ALWAYS call \`remb__conversation_log\` before ending the session.
5. Save important patterns/decisions with \`remb__memory_create\`.

${mcpToolReference()}

## Cross-Project

When told "implement it like in project X", use \`cross_project_search\` to find patterns across projects, then \`context_bundle\` with the other project's slug.`;
}

function generateJetBrainsPrompt(slug: string, apiUrl: string): string {
  return `# Remb — AI Context Management

**Project**: \`${slug}\`
**API**: \`${apiUrl}\`

## Mandatory Session Rules

1. At session start, call \`remb__conversation_history\` and \`remb__memory_load_context\`.
2. After completing significant work, call \`remb__conversation_log\`.
3. Before ending the session, call \`remb__conversation_log\` with a summary.
4. Save important discoveries with \`remb__memory_create\`.

${mcpToolReference()}

## Usage Guide

- **Starting a session**: Load history and context first
- **Need project info**: Use \`project_get\` or \`context_bundle\`
- **Saving knowledge**: \`context_save\` for features, \`memory_create\` for general patterns
- **After code changes**: \`scan_trigger\` to refresh, \`diff_analyze\` for targeted analysis
- **Finishing work**: Always log a summary with \`conversation_log\`
- **Referencing another project**: Use \`cross_project_search\` to find patterns, then \`context_bundle\` with that project's slug`;
}

function generateInstructionsMd(slug: string, apiUrl: string): string {
  return `# Remb — Mandatory Session Protocol

**Project**: \`${slug}\` | **API**: \`${apiUrl}\`

## MANDATORY — Follow These in EVERY Session

### Session Start (do this FIRST, before anything else)
1. Call \`remb__conversation_history\` — load what was discussed and done in prior sessions
2. Call \`remb__memory_load_context\` — load all persistent project memories (core + active tier)

### During Work
3. Call \`remb__conversation_log\` after completing any significant task, bug fix, or feature
4. Call \`remb__memory_create\` when you discover important patterns, decisions, or gotchas worth keeping

### Session End (do this LAST, before the conversation ends)
5. Call \`remb__conversation_log\` with a summary: what was asked, what was done, key decisions made

Skipping these causes knowledge loss across sessions. The user expects you to follow this automatically.

---

${mcpToolReference()}

## When to Use What

| Situation | Tool |
|---|---|
| Starting a session | \`conversation_history\` + \`memory_load_context\` |
| Need project info | \`project_get\` or \`context_bundle\` |
| Saving knowledge | \`context_save\` (feature-specific) or \`memory_create\` (cross-cutting) |
| After code changes | \`scan_trigger\` or \`diff_analyze\` |
| Finishing work | \`conversation_log\` with summary |
| "Do it like in project X" | \`cross_project_search\` → \`context_bundle\` with that project slug |
| Global coding preference | \`memory_create\` with no \`project_id\`, category \`"preference"\` |

## Memory Tiers

- **core** — always loaded into every session automatically
- **active** — loaded on-demand or when relevant to current query
- **archive** — compressed long-term storage

Save architectural decisions and key patterns as \`core\` tier so they're always available.`;
}

function generateClaudeMd(slug: string, apiUrl: string): string {
  return `# Remb — AI Context Management

**Project**: \`${slug}\` | **API**: \`${apiUrl}\`

## MANDATORY — Follow These in EVERY Session

1. At session start, call \`remb__conversation_history\` to load prior session context.
2. At session start, call \`remb__memory_load_context\` to load all project memories.
3. After completing significant work, call \`remb__conversation_log\` to record it.
4. Before ending the session, call \`remb__conversation_log\` with a final summary.
5. Save important patterns/decisions with \`remb__memory_create\`.

${mcpToolReference()}

## Cross-Project

When told "implement it like in project X", use \`cross_project_search\` to find patterns, then \`context_bundle\` with the other project's slug.`;
}

function generateAiderConfig(slug: string, apiUrl: string): string {
  return `# Aider configuration — generated by remb init
# Remb MCP server provides persistent memory tools for this project.
# Run: remb serve   (then configure your MCP client to connect to it)

## remb-instructions
# Project: ${slug}
# API: ${apiUrl}
#
# At the start of each session:
#   1. Call remb__conversation_history to load prior context
#   2. Call remb__memory_load_context to load project memories
#
# During work:
#   - After significant work: remb__conversation_log
#   - Discoveries: remb__memory_create
#
# Before ending:
#   - remb__conversation_log with a summary
`;
}
