import { Command } from "commander";
import { resolve, basename } from "node:path";
import { existsSync, writeFileSync, mkdirSync, readFileSync } from "node:fs";
import { createInterface } from "node:readline";
import { execSync } from "node:child_process";
import chalk from "chalk";
import { writeProjectConfig, findProjectConfig } from "../lib/config.js";
import { createApiClient, ApiError } from "../lib/api-client.js";
import { getApiKey, saveApiKey } from "../lib/credentials.js";
import { success, error, info, keyValue, warn } from "../lib/output.js";

function generateAgentMd(slug: string, apiUrl: string): string {
  return `# Remb — AI Context Management

> This file was generated by \`remb init\`. It documents the Remb CLI so your AI coding assistant knows how to use it.

## Project

- **Slug**: \`${slug}\`
- **API**: \`${apiUrl}\`
- **Config**: \`.remb.yml\` (committed, no secrets)

## What is Remb?

Remb is a persistent memory and context layer for AI coding sessions. It lets you save, retrieve, and scan project context — features, architecture decisions, code patterns — so AI assistants have deep project knowledge across sessions.

## Authentication

The user must be logged in before any command works (except \`init\`).

\`\`\`sh
remb login              # Opens browser OAuth flow
remb login --key <key>  # Direct API key auth
remb whoami             # Check current identity
remb logout             # Clear credentials
\`\`\`

Credentials are stored in \`~/.config/remb/credentials.json\` (never in the repo).

## Commands Reference

### remb init
Initialize a project — creates local config, generates this AI reference doc, and registers the project on the Remb server (if logged in).

\`\`\`sh
remb init                      # Init with directory name as project slug
remb init my-app               # Init with specific name
remb init --force              # Re-initialize (overwrites config + REMB.md)
\`\`\`

**What it does**:
1. Creates \`.remb.yml\` (project config)
2. Generates \`REMB.md\` (this file — AI agent reference)
3. Auto-detects git remote URL, repo name, and branch
4. Registers the project on the Remb server (if authenticated)

If not logged in, run \`remb login\` first, then \`remb init --force\` to register.

### remb scan
Trigger a cloud scan to extract features, code symbols, and architecture from your codebase. Uses a 5-phase AI pipeline (Scout → Analyze → Architect → Review → Finalize). Shows live progress in the terminal.

\`\`\`sh
remb scan                      # Cloud scan via GitHub (recommended)
remb scan --local              # Scan local files (no GitHub needed)
remb scan --local --path src/  # Scan specific subdirectory locally
remb scan -p <slug>            # Scan specific project
remb scan --force              # Skip git pre-flight checks
remb scan --no-poll            # Fire and forget (don't wait for results)
\`\`\`

**Pre-flight checks** (cloud scan): Verifies you're in a git repo, warns about uncommitted changes, checks if local is ahead of remote.

**Local scan** (\`--local\`): Reads files directly from disk, groups them by directory into context entries, and uploads the results. No GitHub access needed — works for offline repos, monorepos, and any directory structure.

**Live progress**: After triggering, polls for scan status and displays progress. During high load, scans queue; the status shows \`queued\` before \`running\`.

**Returns**: \`started\` | \`already_running\` | \`up_to_date\` | \`queued\`

**When to use cloud vs local**:
| Scenario | Use |
|---|---|
| Normal workflow (committed code) | \`remb scan\` |
| No GitHub remote / first setup | \`remb scan --local\` |
| Monorepo sub-project | \`remb scan --local --path packages/my-pkg\` |
| GitHub rate-limited or inaccessible | \`remb scan --local\` |

### remb push
Deprecated alias for \`remb scan\`. Kept for backward compatibility — use \`remb scan\` instead.

\`\`\`sh
remb push        # Same as: remb scan
\`\`\`

### remb save
Save a context entry for a feature.

\`\`\`sh
remb save -f "auth-flow" -c "Uses NextAuth with GitHub OAuth..."
remb save -f "db-schema" -c "PostgreSQL via Supabase with RLS..." -t "database,security"
remb save -f "api-design" --type architecture -c "REST API with..."
\`\`\`

**Options**: \`-f/--feature\` (required), \`-c/--content\` (required), \`-p/--project\`, \`-t/--tags\`, \`--type\`

### remb get
Retrieve saved context entries.

\`\`\`sh
remb get                           # All entries for project
remb get -f "auth-flow"            # Entries for specific feature
remb get -l 10 --format json       # Limit and format output
remb get --format markdown         # Markdown output
\`\`\`

**Formats**: \`table\` (default), \`json\`, \`markdown\`

### remb context
Download the full project context bundle as a single markdown document.

\`\`\`sh
remb context                       # Print to stdout
remb context -o context.md         # Write to file
remb context --json                # JSON format
\`\`\`

This is ideal for feeding full project knowledge into an AI assistant.

### remb diff
Analyze uncommitted git changes and save as context.

\`\`\`sh
remb diff                          # Unstaged changes
remb diff --staged                 # Staged changes only
remb diff --all                    # All changes (staged + unstaged)
\`\`\`

### remb memory
Manage persistent AI memories. Memories have two scopes:
- **Project-scoped** — linked to a specific project (relevant to that codebase only)
- **Global** — no project scope (project_id is null) — apply across ALL projects

\`\`\`sh
remb memory add -t "Title" -c "Content..." --tier core --category architecture
remb memory add -t "Title" -c "Content..." --project my-app  # project-scoped memory
remb memory list                       # All memories (shows [project] or [global] badge)
remb memory list --project my-app      # Project memories + global memories
remb memory list --global              # Only global memories
remb memory list --tier core -s "auth" # Search core-tier memories
remb memory update <id> -c "Updated content..."
remb memory delete <id>
remb memory promote <id> --to core     # Promote to core tier
\`\`\`

**Tiers**: \`core\` (always loaded), \`active\` (session-relevant), \`archive\` (historical)

### remb link
Create dependency relationships between features.

\`\`\`sh
remb link --from "auth-flow" --to "user-profile" --type depends_on
\`\`\`

**Types**: \`depends_on\`, \`extends\`, \`uses\`

### remb projects
List and manage projects. Switch the active project for the current workspace.

\`\`\`sh
remb projects list                           # List all projects
remb projects list --status active           # Filter by status
remb projects list --format json             # JSON output
remb projects use my-app                     # Set active project (writes .remb.yml)
remb projects switch my-app                  # Same as use
\`\`\`

**remb projects use <slug>** looks up the project on the server, confirms it exists, then writes \`.remb.yml\` in the current directory. All subsequent commands will use the new project.

### remb serve
Start a local MCP server for direct AI tool integration (stdio transport).

\`\`\`sh
remb serve                         # Serve current project
remb serve --project <slug>        # Serve specific project
\`\`\`

**Exposed MCP tools**:

Remb exposes **42 MCP tools** via \`remb serve\` (or the hosted endpoint). Below is the complete list:

**Memory Management:**
- \`remb__memory_list\` — list memories (filter by tier, category, search)
- \`remb__memory_search\` — semantic search across all memories
- \`remb__memory_load_context\` — load all core + active memories as context
- \`remb__memory_create\` — create a new memory
- \`remb__memory_update\` — update an existing memory
- \`remb__memory_delete\` — delete a memory
- \`remb__memory_promote\` — promote a memory to a higher tier
- \`remb__memory_stats\` — get memory usage statistics
- \`remb__memory_image_upload\` — upload an image to memory
- \`remb__memory_image_list\` — list stored images

**Conversation Tracking:**
- \`remb__conversation_log\` — record what was discussed or accomplished
- \`remb__conversation_history\` — load recent conversation history

**Project & Context:**
- \`remb__projects_list\` — list all projects with feature counts
- \`remb__project_get\` — get project details, features, and latest scan
- \`remb__context_save\` — save a context entry for a feature
- \`remb__context_get\` — retrieve context entries (optional feature filter)
- \`remb__context_bundle\` — full project context as markdown

**Scanning & Analysis:**
- \`remb__scan_trigger\` — trigger a multi-agent cloud scan
- \`remb__scan_status\` — check scan progress
- \`remb__scan_on_push\` — trigger scan on git push
- \`remb__diff_analyze\` — analyze a git diff and save extracted changes

**Code Graph & Architecture:**
- \`remb__explore_code_graph\` — explore the code graph: functions, classes, layers, edges
- \`remb__search_code_symbols\` — semantic search across code symbols
- \`remb__graph_query\` — query the knowledge graph by entity or feature
- \`remb__graph_related\` — find related entities by name or context

**Plans & Workflow:**
- \`remb__plan_list\` — list development plans
- \`remb__plan_get\` — get plan details with phases
- \`remb__plan_create_phase\` — add a phase to a plan
- \`remb__plan_update_phase\` — update phase status (auto-completes plan when all done)
- \`remb__plan_complete\` — mark a plan as complete
- \`remb__plan_phases\` — list all phases for a plan

**Cross-Project:**
- \`remb__cross_project_search\` — search across ALL projects for features, context, and memories
- \`remb__cross_project_patterns\` — find patterns used across projects
- \`remb__context_bundle\` — also works with other project slugs to load another project's context

**Session & Protocol:**
- \`remb__session_start\` — signal session start; loads context automatically

### Cloud Scan Pipeline

When you run \`remb push\`, the server runs a 5-phase multi-agent pipeline:

1. **Scout** — Fetches file tree, downloads tarball, builds import graph, deduplicates against previous scans
2. **Analyze** — Parallel AI extraction (5 concurrent calls per tier): extracts features, code symbols (functions, classes, hooks, components), and edges (calls, imports, data flows)
3. **Architect** — LLM analyzes aggregated file summaries to produce semantic architecture layers (api, service, data, ui, auth, config, etc.)
4. **Review** — Resolves code edges to actual symbol IDs, validates graph integrity, optionally runs LLM for structural diagnostics
5. **Finalize** — Marks scan complete, schedules continuation if more files remain (max 10 passes)

The result is a rich knowledge graph stored across 4 tables: \`features\`, \`code_nodes\`, \`code_edges\`, \`project_layers\`.

### Code Graph

After scanning, your project has a queryable code graph:

- **code_nodes** — individual functions, classes, components, hooks with their parameters, return types, line numbers, complexity scores, and architecture layer
- **code_edges** — call/import/data-flow relationships between symbols
- **project_layers** — semantic architecture zones with auto-detected file patterns

The AI can explore this graph with \`explore_code_graph\` (filter by file, type, layer) and \`search_code_symbols\` (semantic search across all symbols).

### Plans

The AI can create and manage development plans:

\`\`\`
remb__plan_list           → see all plans for the project
remb__plan_get <id>       → phases, status, per-phase details
remb__plan_create_phase   → add a new phase to a plan
remb__plan_update_phase   → mark phase complete (auto-completes plan when all phases done)
\`\`\`

### Cross-Project Intelligence

Search memories and patterns across ALL your projects:

\`\`\`
remb__cross_project_search("authentication pattern")
→ Returns memories, features, and context entries from every project that matches
\`\`\`

Load another project's full context to apply its patterns:

\`\`\`
remb__context_bundle("other-project-slug")
→ Returns complete markdown context for that project
\`\`\`

### remb history
View conversation history — see what AI discussed and did across sessions.

\`\`\`sh
remb history                           # Last 20 entries as timeline
remb history --date 2025-03-15         # Single day
remb history --from 2025-03-01 --to 2025-03-15  # Date range
remb history --limit 50                # More entries
remb history --format markdown         # Markdown output
remb history --format json             # Raw JSON
remb history -p <slug>                 # Filter by project
\`\`\`

**MCP tools** (available when connected via \`remb serve\` or the hosted MCP endpoint):
- \`conversation_log\` — record what you discussed or accomplished (call after completing work)
- \`conversation_history\` — load recent conversation history (call at session start to catch up)

## Step-by-Step Workflows

Follow these workflows in order. Each numbered step must complete before proceeding to the next.

### 1. First-time project setup

1. **Authenticate** — \`remb login\` (opens browser OAuth or use \`--key <key>\`)
2. **Initialize** — \`remb init\` (creates \`.remb.yml\`, generates \`REMB.md\`, registers project on server)
3. **First scan** — \`remb push\` (triggers cloud scan, shows live progress until complete)
4. **Verify** — \`remb projects list\` (confirm project appears with \`active\` status)

### 2. Update context after code changes

1. **Commit & push** — \`git add . && git commit -m "feat: ..." && git push\`
2. **Trigger scan** — \`remb push\` (detects new commits, runs cloud scan with progress)
3. **Wait for completion** — the CLI shows a progress bar; wait for \`Scan complete\` message

### 3. Save knowledge manually

1. **Save a feature** — \`remb save -f "feature-name" -c "Description..."\`
2. **Verify** — \`remb get -f "feature-name"\` (confirm entry was stored)

### 4. Load full context into AI session

1. **Bundle context** — \`remb context -o CONTEXT.md\`
2. **Feed to AI** — provide the generated \`CONTEXT.md\` file to your AI assistant

### 5. Analyze local changes before committing

1. **Make edits** — modify source files as needed
2. **Diff analysis** — \`remb diff --all\` (analyzes all staged + unstaged changes)
3. **Review** — check the generated context entries summarizing your changes

### 6. Local scan (no git / no GitHub required)

Use this when the repo isn't on GitHub, has no git remote, or you want to scan a specific subdirectory.

1. **Preview first** — \`remb scan --dry-run\` (see what directories will be scanned, no upload)
2. **Full scan** — \`remb scan\` (uploads all directory-grouped context entries)
3. **Verify** — \`remb get\` (confirm entries appear in the project)
4. **Targeted scan** — \`remb scan --path src/ --depth 3\` to narrow the scope

## MCP Integration

Add Remb as an MCP server in your IDE for direct AI tool access:

**Cursor / VS Code** (\`.cursor/mcp.json\` or \`.vscode/mcp.json\`):
\`\`\`json
{
  "mcpServers": {
    "remb": {
      "command": "remb",
      "args": ["serve"]
    }
  }
}
\`\`\`

Or connect to the hosted endpoint at \`${apiUrl}/api/mcp\` for aggregated MCP access with all your connected servers.

## Exit Codes

- \`0\` — Success
- \`1\` — Error (auth failure, network error, validation error)

All commands respect the \`-p/--project <slug>\` flag or fall back to \`.remb.yml\` in the current directory tree.
`;
}

export const initCommand = new Command("init")
  .description("Initialize a project with remb tracking")
  .argument("[project-name]", "Project name (defaults to directory name)")
  .option("--api-url <url>", "API server URL", "https://www.useremb.com")
  .option("--force", "Overwrite existing configuration", false)
  .option(
    "--ide <ide>",
    "IDE to configure (vscode, cursor, windsurf, cline, jetbrains, claude, aider, all)",
  )
  .action(async (projectName: string | undefined, opts) => {
    const cwd = process.cwd();
    const name = projectName ?? basename(cwd);

    // Generate a slug
    const slug = name
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-|-$/g, "");

    if (!slug) {
      error("Invalid project name — must contain at least one alphanumeric character.");
      process.exit(1);
    }

    // Check for existing config
    const existing = findProjectConfig(cwd);
    if (existing && !opts.force) {
      warn(`Already initialized at ${chalk.dim(existing.dir + "/.remb.yml")}`);
      info(`Use ${chalk.bold("--force")} to overwrite.`);
      return;
    }

    // Determine IDE: flag > existing config > interactive prompt > auto-detect
    const ide = await resolveIde(opts.ide, existing?.config.ide);

    const filePath = writeProjectConfig(cwd, {
      project: slug,
      api_url: opts.apiUrl,
      ide,
    });

    // Generate AI agent reference doc
    const agentMdPath = resolve(cwd, "REMB.md");
    writeFileSync(agentMdPath, generateAgentMd(slug, opts.apiUrl), "utf-8");

    console.log();
    success(`Project ${chalk.bold(slug)} initialized!`);
    keyValue("Config", filePath);
    keyValue("Agent docs", agentMdPath);
    keyValue("Project", slug);
    keyValue("API URL", opts.apiUrl);
    keyValue("IDE", ide);
    console.log();

    // Auto-register project on server if logged in (or offer to sign in)
    let apiKey = getApiKey();
    if (!apiKey && process.stdout.isTTY) {
      console.log(
        chalk.dim("  You're not signed in — signing in lets Remb register your project and sync context.")
      );
      const shouldLogin = await promptYesNo("  Sign in now?");
      if (shouldLogin) {
        apiKey = await runInlineLogin(opts.apiUrl);
      }
    }

    if (apiKey) {
      try {
        // Auto-detect git info
        let repoUrl: string | undefined;
        let repoName: string | undefined;
        let branch: string | undefined;
        try {
          repoUrl = execSync("git remote get-url origin", { cwd, encoding: "utf-8" }).trim();
          const match = repoUrl.match(/[/:]([-\w.]+\/[-\w.]+?)(?:\.git)?$/);
          if (match) repoName = match[1];
          branch = execSync("git rev-parse --abbrev-ref HEAD", { cwd, encoding: "utf-8" }).trim();
        } catch {
          // Not a git repo or no remote — fine
        }

        const client = createApiClient({ apiUrl: opts.apiUrl, apiKey });
        const { project } = await client.createProject({
          name: slug,
          repoUrl,
          repoName,
          branch,
        });
        success(`Project registered on Remb ${chalk.dim(`(${project.slug})`)}`);
      } catch (err) {
        if (err instanceof ApiError && err.statusCode === 409) {
          info(`Project ${chalk.bold(slug)} already exists on server — linked.`);
        } else {
          warn(`Could not register project on server: ${err instanceof Error ? err.message : "unknown error"}`);
          info(`You can register it later from the dashboard.`);
        }
      }
    } else if (!getApiKey()) {
      info(`Run ${chalk.bold("remb login")} to register this project on the server.`);
    }

    // Check for .gitignore and suggest adding credentials
    const gitignorePath = resolve(cwd, ".gitignore");
    if (existsSync(gitignorePath)) {
      info(
        `${chalk.dim("Tip:")} .remb.yml and REMB.md are safe to commit — they contain no secrets.`
      );
    }

    // Inject into IDE-specific instruction folders
    const injected = injectIntoIDEContextFiles(cwd, slug, opts.apiUrl, ide);
    if (injected.length > 0) {
      info(`AI context injected into: ${injected.map((p) => chalk.dim(p)).join(", ")}`);
    }

    info(
      `${chalk.bold("REMB.md")} generated — your IDE's AI agent can read it to learn all Remb commands.`
    );

    // Offer to install recommended skills
    try {
      const installSkills = await promptYesNo(
        "Install recommended AI skills (remb-context, remb-memory, remb-scan)?"
      );
      if (installSkills) {
        info("Installing skills...");
        const { installSkillsAfterInit } = await import("./skills.js");
        await installSkillsAfterInit(cwd, ide);
      }
    } catch {
      // Non-interactive or user declined — skip silently
    }
  });

function injectIntoIDEContextFiles(cwd: string, slug: string, apiUrl: string, ide: string): string[] {
  const START_MARKER = "<!-- remb:start -->";
  const END_MARKER = "<!-- remb:end -->";

  const all = ide === "all";
  const is = (name: string) => all || ide === name;

  type Target = {
    path: string;
    label: string;
    content: string;
    enabled: boolean;
    fileHeader?: string; // static content prepended before the remb block (e.g. YAML frontmatter)
  };

  const targets: Target[] = [
    {
      path: resolve(cwd, ".cursor", "rules", "remb.mdc"),
      label: ".cursor/rules/remb.mdc",
      content: generateCursorRules(slug, apiUrl),
      enabled: is("cursor"),
    },
    {
      path: resolve(cwd, ".windsurfrules"),
      label: ".windsurfrules",
      content: generateWindsurfRules(slug, apiUrl),
      enabled: is("windsurf"),
    },
    {
      path: resolve(cwd, ".clinerules"),
      label: ".clinerules",
      content: generateClineRules(slug, apiUrl),
      enabled: is("cline"),
    },
    {
      path: resolve(cwd, ".junie", "guidelines.md"),
      label: ".junie/guidelines.md",
      content: generateJetBrainsPrompt(slug, apiUrl),
      enabled: is("jetbrains"),
    },
    {
      path: resolve(cwd, "CLAUDE.md"),
      label: "CLAUDE.md",
      content: generateClaudeMd(slug, apiUrl),
      enabled: is("claude"),
    },
    {
      path: resolve(cwd, ".aider.conf.yml"),
      label: ".aider.conf.yml",
      content: generateAiderConfig(slug, apiUrl),
      enabled: is("aider"),
    },
    {
      path: resolve(cwd, ".github", "instructions", "remb-session.instructions.md"),
      label: ".github/instructions/remb-session.instructions.md",
      content: generateInstructionsMd(slug, apiUrl),
      enabled: is("vscode"),
      fileHeader: "---\napplyTo: '**'\n---",
    },
  ];

  const injected: string[] = [];

  for (const target of targets) {
    if (!target.enabled) continue;

    try {
      const dir = resolve(target.path, "..");
      if (!existsSync(dir)) {
        mkdirSync(dir, { recursive: true });
      }

      const block = `${START_MARKER}\n${target.content}\n${END_MARKER}`;
      const header = target.fileHeader ? target.fileHeader + "\n\n" : "";

      if (existsSync(target.path)) {
        const existing = readFileSync(target.path, "utf-8");
        const startIdx = existing.indexOf(START_MARKER);
        const endIdx = existing.indexOf(END_MARKER);
        if (startIdx !== -1 && endIdx !== -1) {
          // Markers found — surgically replace only the remb block
          const updated =
            existing.slice(0, startIdx) +
            block +
            existing.slice(endIdx + END_MARKER.length);
          writeFileSync(target.path, updated);
        } else if (target.fileHeader) {
          // File exists but unmanaged (no markers) — adopt it: write header + block
          writeFileSync(target.path, header + block + "\n");
        } else {
          // Append block after existing content
          writeFileSync(target.path, existing.trimEnd() + "\n\n" + block + "\n");
        }
      } else {
        writeFileSync(target.path, header + block + "\n");
      }

      injected.push(target.label);
    } catch {
      // Silently skip files we can't write
    }
  }

  // Auto-generate MCP config files
  const mcpConfig = JSON.stringify({
    mcpServers: {
      remb: { command: "remb", args: ["serve"] },
    },
  }, null, 2);

  if (is("vscode")) {
    const vscMcp = resolve(cwd, ".vscode", "mcp.json");
    if (!existsSync(vscMcp)) {
      try {
        mkdirSync(resolve(cwd, ".vscode"), { recursive: true });
        writeFileSync(vscMcp, mcpConfig + "\n");
        injected.push(".vscode/mcp.json");
      } catch { /* skip */ }
    }
  }

  if (is("cursor")) {
    const cursorMcp = resolve(cwd, ".cursor", "mcp.json");
    if (!existsSync(cursorMcp)) {
      try {
        mkdirSync(resolve(cwd, ".cursor"), { recursive: true });
        writeFileSync(cursorMcp, mcpConfig + "\n");
        injected.push(".cursor/mcp.json");
      } catch { /* skip */ }
    }
  }

  return injected;
}

// ─── Inline Login ─────────────────────────────────────────────────────────────

async function promptYesNo(message: string): Promise<boolean> {
  const rl = createInterface({ input: process.stdin, output: process.stdout });
  return new Promise((resolve) => {
    rl.question(`${message} ${chalk.dim("[Y/n]")}: `, (answer) => {
      rl.close();
      const a = answer.trim().toLowerCase();
      resolve(a === "" || a === "y" || a === "yes");
    });
  });
}

/** Open a URL in the user's default browser. */
async function openBrowser(url: string): Promise<void> {
  const { exec } = await import("node:child_process");
  const { platform } = await import("node:os");
  const os = platform();
  const cmd =
    os === "darwin" ? "open" :
    os === "win32" ? "start" :
    "xdg-open";
  exec(`${cmd} ${JSON.stringify(url)}`);
}

/** Run browser OAuth inline and return the API key, or null on failure. */
async function runInlineLogin(apiUrl: string): Promise<string | null> {
  const baseUrl = apiUrl.replace(/\/+$/, "");
  try {
    const res = await fetch(`${baseUrl}/api/cli/auth/start`, { method: "POST" });
    if (!res.ok) {
      warn("Could not start login flow.");
      return null;
    }

    const { state, authUrl } = await res.json() as { state: string; authUrl: string };

    console.log();
    info("Opening browser to authenticate...");
    console.log(chalk.dim(`  If the browser doesn't open, visit:`));
    console.log(chalk.dim(`  ${authUrl}`));

    await openBrowser(authUrl);

    const ora = (await import("ora")).default;
    const spinner = ora("Waiting for browser authentication...").start();

    const deadline = Date.now() + 120_000;
    while (Date.now() < deadline) {
      await new Promise((r) => setTimeout(r, 2_000));
      try {
        const poll = await fetch(`${baseUrl}/api/cli/auth/poll?state=${encodeURIComponent(state)}`);
        if (!poll.ok) continue;
        const data = await poll.json() as { status: string; apiKey?: string; login?: string };
        if (data.status === "completed" && data.apiKey) {
          spinner.stop();
          const path = saveApiKey(data.apiKey);
          console.log();
          success(`Authenticated${data.login ? ` as ${chalk.bold(data.login)}` : ""}!`);
          keyValue("Credentials", path);
          console.log();
          return data.apiKey;
        }
        if (data.status === "expired") break;
      } catch { /* retry */ }
    }

    spinner.fail("Login timed out.");
    return null;
  } catch {
    warn("Login failed — you can run `remb login` separately.");
    return null;
  }
}

// ─── IDE Resolution ───────────────────────────────────────────────────────────

const VALID_IDES = ["vscode", "cursor", "windsurf", "cline", "jetbrains", "claude", "aider", "all"] as const;
type IDE = typeof VALID_IDES[number];

const IDE_LABELS: Record<IDE, string> = {
  vscode:    "VS Code (GitHub Copilot)",
  cursor:    "Cursor",
  windsurf:  "Windsurf",
  cline:     "Cline",
  jetbrains: "JetBrains AI",
  claude:    "Claude Code",
  aider:     "Aider",
  all:       "All / Multiple IDEs",
};

/** Try to detect the IDE from environment variables and running processes. */
function detectIde(): string | null {
  const env = process.env;

  // VS Code sets TERM_PROGRAM=vscode in its integrated terminal
  if (env.TERM_PROGRAM === "vscode" || env.VSCODE_PID) return "vscode";

  // Cursor sets TERM_PROGRAM=cursor (it's an Electron fork of VS Code)
  if (env.TERM_PROGRAM === "cursor") return "cursor";

  // Windsurf sets TERM_PROGRAM=Windsurf
  if (env.TERM_PROGRAM?.toLowerCase() === "windsurf") return "windsurf";

  // JetBrains IDEs set TERMINAL_EMULATOR=JetBrains-JediTerm
  if (env.TERMINAL_EMULATOR?.includes("JetBrains")) return "jetbrains";

  // Claude Code typically runs via `claude` CLI — check parent command name
  if (env.CLAUDE_CODE === "1" || env.TERM_PROGRAM === "claude") return "claude";

  return null;
}

async function resolveIde(flagValue: string | undefined, configValue: string | undefined): Promise<string> {
  if (flagValue) {
    const normalized = flagValue.toLowerCase();
    if (!(VALID_IDES as readonly string[]).includes(normalized)) {
      warn(`Unknown IDE "${flagValue}". Valid options: ${VALID_IDES.join(", ")}`);
      warn("Falling back to: all");
      return "all";
    }
    return normalized;
  }

  if (configValue && (VALID_IDES as readonly string[]).includes(configValue)) {
    return configValue;
  }

  // Try auto-detection from environment
  const detected = detectIde();
  if (detected) {
    info(`Detected IDE: ${chalk.bold(IDE_LABELS[detected as IDE])}`);
    return detected;
  }

  // Interactive prompt when running in a real terminal
  if (process.stdout.isTTY) {
    return promptIde();
  }

  return "all";
}

async function promptIde(): Promise<string> {
  const rl = createInterface({ input: process.stdin, output: process.stdout });
  const choices = VALID_IDES.map((v, i) => ({ key: String(i + 1), value: v, label: IDE_LABELS[v] }));

  console.log();
  console.log(chalk.bold("  Which IDE are you using?"));
  console.log();
  for (const c of choices) {
    console.log(`    ${chalk.dim(c.key + ".")} ${c.label}`);
  }
  console.log();

  return new Promise((resolve) => {
    rl.question(chalk.bold("  Enter number: "), (answer) => {
      rl.close();
      const found = choices.find((c) => c.key === answer.trim());
      if (!found) {
        console.log(chalk.dim("  No selection — using: all"));
        resolve("all");
      } else {
        console.log(chalk.dim(`  Selected: ${found.label}`));
        resolve(found.value);
      }
    });
  });
}

// ─── IDE-Specific Generators ─────────────────────────────────────────────────

function mcpToolReference(): string {
  return `### Available MCP Tools

**Memory Management:**
- \`remb__memory_list\` — list memories (filter by tier, category, search)
- \`remb__memory_search\` — semantic search across all memories
- \`remb__memory_load_context\` — load all core + active memories as context
- \`remb__memory_create\` — create a new memory
- \`remb__memory_update\` — update an existing memory
- \`remb__memory_delete\` — delete a memory
- \`remb__memory_promote\` — promote a memory to a higher tier
- \`remb__memory_stats\` — get memory usage statistics
- \`remb__memory_image_upload\` — upload an image to memory
- \`remb__memory_image_list\` — list stored images

**Conversation Tracking:**
- \`remb__conversation_log\` — record what you discussed or accomplished
- \`remb__conversation_history\` — load recent conversation history

**Project & Context:**
- \`remb__projects_list\` — list all projects with feature counts
- \`remb__project_get\` — get project details, features, and latest scan
- \`remb__context_save\` — save a context entry for a feature
- \`remb__context_get\` — retrieve context entries (optional feature filter)
- \`remb__context_bundle\` — full project context as markdown

**Scanning & Analysis:**
- \`remb__scan_trigger\` — trigger a cloud scan
- \`remb__scan_status\` — check scan progress
- \`remb__diff_analyze\` — analyze a git diff and save extracted changes

**Cross-Project:**
- \`remb__cross_project_search\` — search across ALL projects for features, context, and memories
- \`remb__context_bundle\` — also works with other project slugs to load another project's full context
- \`remb__memory_create\` — create with no project_id to save global preferences that apply everywhere`;
}

function generateCursorRules(slug: string, apiUrl: string): string {
  return `---
description: Remb context management — mandatory rules for AI sessions
globs: "**"
alwaysApply: true
---

# Remb — AI Context Management

**Project**: \`${slug}\` | **API**: \`${apiUrl}\`

## MANDATORY Rules

1. At session start, call \`remb__conversation_history\` and \`remb__memory_load_context\`.
2. After completing significant work, call \`remb__conversation_log\` to record it.
3. Before ending the session, call \`remb__conversation_log\` with a final summary.
4. Save important discoveries with \`remb__memory_create\`.

${mcpToolReference()}

## Usage Patterns

| Situation | Tool |
|---|---|
| Starting a session | \`conversation_history\` + \`memory_load_context\` |
| Need project info | \`project_get\` or \`context_bundle\` |
| Saving knowledge | \`context_save\` or \`memory_create\` |
| After code changes | \`scan_trigger\` or \`diff_analyze\` |
| Finishing work | \`conversation_log\` |
| Reference another project | \`cross_project_search\` + \`context_bundle\` |`;
}

function generateWindsurfRules(slug: string, apiUrl: string): string {
  return `# Remb — AI Context Management

Project: ${slug} | API: ${apiUrl}

## MANDATORY — Follow These Every Session

1. Session start → call \`remb__conversation_history\` and \`remb__memory_load_context\`
2. After significant work → call \`remb__conversation_log\`
3. Before ending → call \`remb__conversation_log\` with summary
4. Discoveries → call \`remb__memory_create\`

${mcpToolReference()}

## Quick Reference

- Starting: conversation_history + memory_load_context
- Project info: project_get or context_bundle
- Save knowledge: context_save (feature) or memory_create (general)
- After changes: scan_trigger or diff_analyze
- Finishing: conversation_log
- Reference another project: cross_project_search + context_bundle`;
}

function generateClineRules(slug: string, apiUrl: string): string {
  return `# Remb — AI Context Management

Project: ${slug} | API: ${apiUrl}

## MANDATORY Rules

These rules MUST be followed in every session:

1. ALWAYS call \`remb__conversation_history\` at session start to load prior context.
2. ALWAYS call \`remb__memory_load_context\` at session start to load project memories.
3. ALWAYS call \`remb__conversation_log\` after completing significant work.
4. ALWAYS call \`remb__conversation_log\` before ending the session.
5. Save important patterns/decisions with \`remb__memory_create\`.

${mcpToolReference()}

## Cross-Project

When told "implement it like in project X", use \`cross_project_search\` to find patterns across projects, then \`context_bundle\` with the other project's slug.`;
}

function generateJetBrainsPrompt(slug: string, apiUrl: string): string {
  return `# Remb — AI Context Management

**Project**: \`${slug}\`
**API**: \`${apiUrl}\`

## Mandatory Session Rules

1. At session start, call \`remb__conversation_history\` and \`remb__memory_load_context\`.
2. After completing significant work, call \`remb__conversation_log\`.
3. Before ending the session, call \`remb__conversation_log\` with a summary.
4. Save important discoveries with \`remb__memory_create\`.

${mcpToolReference()}

## Usage Guide

- **Starting a session**: Load history and context first
- **Need project info**: Use \`project_get\` or \`context_bundle\`
- **Saving knowledge**: \`context_save\` for features, \`memory_create\` for general patterns
- **After code changes**: \`scan_trigger\` to refresh, \`diff_analyze\` for targeted analysis
- **Finishing work**: Always log a summary with \`conversation_log\`
- **Referencing another project**: Use \`cross_project_search\` to find patterns, then \`context_bundle\` with that project's slug`;
}

function generateInstructionsMd(slug: string, apiUrl: string): string {
  return `# Remb — Mandatory Session Protocol

**Project**: \`${slug}\` | **API**: \`${apiUrl}\`

## MANDATORY — Follow These in EVERY Session

### Session Start (do this FIRST, before anything else)
1. Call \`remb__conversation_history\` — load what was discussed and done in prior sessions
2. Call \`remb__memory_load_context\` — load all persistent project memories (core + active tier)

### During Work
3. Call \`remb__conversation_log\` after completing any significant task, bug fix, or feature
4. Call \`remb__memory_create\` when you discover important patterns, decisions, or gotchas worth keeping

### Session End (do this LAST, before the conversation ends)
5. Call \`remb__conversation_log\` with a summary: what was asked, what was done, key decisions made

Skipping these causes knowledge loss across sessions. The user expects you to follow this automatically.

---

${mcpToolReference()}

## When to Use What

| Situation | Tool |
|---|---|
| Starting a session | \`conversation_history\` + \`memory_load_context\` |
| Need project info | \`project_get\` or \`context_bundle\` |
| Saving knowledge | \`context_save\` (feature-specific) or \`memory_create\` (cross-cutting) |
| After code changes | \`scan_trigger\` or \`diff_analyze\` |
| Finishing work | \`conversation_log\` with summary |
| "Do it like in project X" | \`cross_project_search\` → \`context_bundle\` with that project slug |
| Global coding preference | \`memory_create\` with no \`project_id\`, category \`"preference"\` |

## Cross-Project Referencing

When the user says "do it like I did in project X" or references another project:

1. Call \`remb__projects_list\` to find available projects
2. Call \`remb__cross_project_search\` with the concept to find matching patterns across all projects
3. Call \`remb__context_bundle\` with the other project's slug to load its full context
4. Apply the patterns from that project to the current work

**Global preferences** — memories created without a project_id apply to ALL projects. Use \`remb__memory_create\` with category "preference" and no project_id to save cross-project coding standards.

## Memory Tiers

- **core** — always loaded into every session automatically
- **active** — loaded on-demand or when relevant to current query
- **archive** — compressed long-term storage

Save architectural decisions and key patterns as \`core\` tier so they're always available.`;
}

function generateClaudeMd(slug: string, apiUrl: string): string {
  return `# Remb — AI Context Management

**Project**: \`${slug}\` | **API**: \`${apiUrl}\`

## MANDATORY — Follow These in EVERY Session

1. At session start, call \`remb__conversation_history\` to load prior session context.
2. At session start, call \`remb__memory_load_context\` to load all project memories.
3. After completing significant work, call \`remb__conversation_log\` to record it.
4. Before ending the session, call \`remb__conversation_log\` with a final summary.
5. Save important patterns/decisions with \`remb__memory_create\`.

${mcpToolReference()}

## Cross-Project

When told "implement it like in project X", use \`cross_project_search\` to find patterns, then \`context_bundle\` with the other project's slug.`;
}

function generateAiderConfig(slug: string, apiUrl: string): string {
  return `# Aider configuration — generated by remb init
# Remb MCP server provides persistent memory tools for this project.
# Run: remb serve   (then configure your MCP client to connect to it)

## remb-instructions
# Project: ${slug}
# API: ${apiUrl}
#
# At the start of each session:
#   1. Call remb__conversation_history to load prior context
#   2. Call remb__memory_load_context to load project memories
#
# During work:
#   - After significant work: remb__conversation_log
#   - Discoveries: remb__memory_create
#
# Before ending:
#   - remb__conversation_log with a summary
`;
}
