import { resolve, dirname } from "node:path";
import { existsSync, readFileSync, writeFileSync, mkdirSync } from "node:fs";

const CONFIG_FILENAME = ".remb.yml";

export interface ProjectConfig {
  project: string;
  api_url: string;
  ide?: string;
}

const DEFAULT_API_URL = "https://www.useremb.com";

/**
 * Walk up from `cwd` looking for .remb.yml.
 * Returns the parsed config + the directory it was found in, or null.
 */
export function findProjectConfig(
  cwd: string = process.cwd()
): { config: ProjectConfig; dir: string } | null {
  let dir = resolve(cwd);

  while (true) {
    const candidate = resolve(dir, CONFIG_FILENAME);
    if (existsSync(candidate)) {
      const raw = readFileSync(candidate, "utf-8");
      // Lightweight YAML parse — import dynamically to keep startup fast
      const parsed = parseSimpleYaml(raw);
      return {
        config: {
          project: parsed.project ?? "",
          api_url: parsed.api_url ?? DEFAULT_API_URL,
          ide: parsed.ide || undefined,
        },
        dir,
      };
    }
    const parent = dirname(dir);
    if (parent === dir) break;
    dir = parent;
  }

  return null;
}

/**
 * Write a .remb.yml file in the given directory.
 */
export function writeProjectConfig(
  dir: string,
  config: ProjectConfig
): string {
  const filePath = resolve(dir, CONFIG_FILENAME);
  const lines = [
    "# Remb project configuration",
    `# Generated by remb init`,
    "",
    `project: ${config.project}`,
    `api_url: ${config.api_url}`,
  ];
  if (config.ide) lines.push(`ide: ${config.ide}`);
  lines.push("");
  const content = lines.join("\n");

  mkdirSync(dir, { recursive: true });
  writeFileSync(filePath, content, "utf-8");
  return filePath;
}

/**
 * Parse simple key: value YAML without pulling in the full yaml package.
 * Handles the flat structure we use in .remb.yml.
 */
function parseSimpleYaml(raw: string): Record<string, string> {
  const result: Record<string, string> = {};
  for (const line of raw.split("\n")) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const idx = trimmed.indexOf(":");
    if (idx === -1) continue;
    const key = trimmed.slice(0, idx).trim();
    let value = trimmed.slice(idx + 1).trim();
    // Strip surrounding quotes
    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }
    result[key] = value;
  }
  return result;
}
