package cmd

import (
	"bufio"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"strings"

	"github.com/richie/remb/internal/api"
	"github.com/richie/remb/internal/config"
	"github.com/richie/remb/internal/credentials"
	"github.com/richie/remb/internal/output"
	"github.com/spf13/cobra"
)

var initAPIURL string
var initForce bool
var initIDE string

var validIDEs = []struct {
	value string
	label string
}{
	{"vscode", "VS Code (GitHub Copilot)"},
	{"cursor", "Cursor"},
	{"windsurf", "Windsurf"},
	{"cline", "Cline"},
	{"jetbrains", "JetBrains AI"},
	{"claude", "Claude Code"},
	{"aider", "Aider"},
	{"all", "All / Multiple IDEs"},
}

var initCmd = &cobra.Command{
	Use:   "init [project-name]",
	Short: "Initialize a project with remb tracking",
	Args:  cobra.MaximumNArgs(1),
	Run:   runInit,
}

func init() {
	initCmd.Flags().StringVar(&initAPIURL, "api-url", config.DefaultAPIURL, "API server URL")
	initCmd.Flags().BoolVar(&initForce, "force", false, "Overwrite existing configuration")
	initCmd.Flags().StringVar(&initIDE, "ide", "", "IDE to configure (vscode, cursor, windsurf, cline, jetbrains, claude, aider, all)")
}

func generateAgentMd(slug, apiURL string) string {
	return fmt.Sprintf(`# Remb — AI Context Management

> This file was generated by `+"`remb init`"+`. It documents the Remb CLI so your AI coding assistant knows how to use it.

## Project

- **Slug**: `+"`%s`"+`
- **API**: `+"`%s`"+`
- **Config**: `+"`.remb.yml`"+` (committed, no secrets)

## What is Remb?

Remb is a persistent memory and context layer for AI coding sessions. It lets you save, retrieve, and scan project context — features, architecture decisions, code patterns — so AI assistants have deep project knowledge across sessions.

## Authentication

The user must be logged in before any command works (except `+"`init`"+`).

`+"```"+`sh
remb login              # Opens browser OAuth flow
remb login --key <key>  # Direct API key auth
remb whoami             # Check current identity
remb logout             # Clear credentials
`+"```"+`

Credentials are stored in `+"`~/.config/remb/credentials.json`"+` (never in the repo).

## Commands Reference

### remb init
Initialize a project — creates local config, generates this AI reference doc, and registers the project on the Remb server (if logged in).

`+"```"+`sh
remb init                      # Init with directory name as project slug
remb init my-app               # Init with specific name
remb init --force              # Re-initialize (overwrites config + REMB.md)
`+"```"+`

**What it does**:
1. Creates `+"`.remb.yml`"+` (project config)
2. Generates `+"`REMB.md`"+` (this file — AI agent reference)
3. Auto-detects git remote URL, repo name, and branch
4. Registers the project on the Remb server (if authenticated)

If not logged in, run `+"`remb login`"+` first, then `+"`remb init --force`"+` to register.

### remb push
Trigger a cloud scan to update project context after pushing code. Shows live progress with percentage and per-file status in the terminal.

`+"```"+`sh
remb push                      # Scan current project (with live progress)
remb push -p <slug>            # Scan specific project
remb push --force              # Skip git pre-flight checks
remb push --no-progress        # Fire and forget (don't wait for results)
`+"```"+`

**Pre-flight checks**: Verifies you're in a git repo, warns about uncommitted changes, checks if local is ahead of remote.

**Live progress**: After triggering, polls for scan status and displays a progress bar with percentage, files scanned, and per-file logs (✓ done, ○ skipped, ✗ error).

**Returns**: `+"`started`"+` | `+"`already_running`"+` | `+"`up_to_date`"+`

### remb scan
Auto-scan a directory and generate context entries locally.

`+"```"+`sh
remb scan                        # Scan current directory
remb scan -p <slug> --path src/  # Scan specific path
remb scan --depth 3              # Limit directory depth
remb scan --dry-run              # Preview without saving
remb scan --ignore "test,dist"   # Skip directories
`+"```"+`

### remb save
Save a context entry for a feature.

`+"```"+`sh
remb save -f "auth-flow" -c "Uses NextAuth with GitHub OAuth..."
remb save -f "db-schema" -c "PostgreSQL via Supabase with RLS..." -t "database,security"
remb save -f "api-design" --type architecture -c "REST API with..."
`+"```"+`

**Options**: `+"`-f/--feature`"+` (required), `+"`-c/--content`"+` (required), `+"`-p/--project`"+`, `+"`-t/--tags`"+`, `+"`--type`"+`

### remb get
Retrieve saved context entries.

`+"```"+`sh
remb get                           # All entries for project
remb get -f "auth-flow"            # Entries for specific feature
remb get -l 10 --format json       # Limit and format output
remb get --format markdown         # Markdown output
`+"```"+`

**Formats**: `+"`table`"+` (default), `+"`json`"+`, `+"`markdown`"+`

### remb context
Download the full project context bundle as a single markdown document.

`+"```"+`sh
remb context                       # Print to stdout
remb context -o context.md         # Write to file
remb context --json                # JSON format
`+"```"+`

This is ideal for feeding full project knowledge into an AI assistant.

### remb diff
Analyze uncommitted git changes and save as context.

`+"```"+`sh
remb diff                          # Unstaged changes
remb diff --staged                 # Staged changes only
remb diff --all                    # All changes (staged + unstaged)
`+"```"+`

### remb memory
Manage persistent AI memories (knowledge that persists across sessions).

`+"```"+`sh
remb memory add -t "Title" -c "Content..." --tier core --category architecture
remb memory list                     # List all memories
remb memory list --tier core -s "auth" # Search core-tier memories
remb memory update <id> -c "Updated content..."
remb memory delete <id>
remb memory promote <id> --to core   # Promote to core tier
`+"```"+`

**Tiers**: `+"`core`"+` (always loaded), `+"`active`"+` (session-relevant), `+"`archive`"+` (historical)

### remb link
Create dependency relationships between features.

`+"```"+`sh
remb link --from "auth-flow" --to "user-profile" --type depends_on
`+"```"+`

**Types**: `+"`depends_on`"+`, `+"`extends`"+`, `+"`uses`"+`

### remb projects
List and manage projects.

`+"```"+`sh
remb projects list
remb projects list --status active --format json
`+"```"+`

### remb serve
Start a local MCP server for direct AI tool integration (stdio transport).

`+"```"+`sh
remb serve                         # Serve current project
remb serve --project <slug>        # Serve specific project
`+"```"+`

**Exposed MCP tools**:
- `+"`save_context`"+` — persist knowledge about a feature
- `+"`get_context`"+` — recall entries (with optional feature filter)
- `+"`load_project_context`"+` — full project bundle as markdown
- `+"`analyze_diff`"+` — AI-analyze uncommitted git changes

### remb history
View conversation history — see what AI discussed and did across sessions.

`+"```"+`sh
remb history                           # Last 20 entries as timeline
remb history --date 2025-03-15         # Single day
remb history --from 2025-03-01 --to 2025-03-15  # Date range
remb history --limit 50                # More entries
remb history --format markdown         # Markdown output
remb history --format json             # Raw JSON
remb history -p <slug>                 # Filter by project
`+"```"+`

**MCP conversation tools** (available when connected via MCP):
- `+"`remb__conversation_log`"+` — record what you discussed or accomplished (call after completing work)
- `+"`remb__conversation_history`"+` — load recent conversation history (call at session start to catch up)

## Step-by-Step Workflows

Follow these workflows in order. Each numbered step must complete before proceeding to the next.

### 1. First-time project setup

1. **Authenticate** — `+"`remb login`"+` (opens browser OAuth or use `+"`--key <key>`"+`)
2. **Initialize** — `+"`remb init`"+` (creates `+"`.remb.yml`"+`, generates `+"`REMB.md`"+`, registers project on server)
3. **First scan** — `+"`remb push`"+` (triggers cloud scan, shows live progress until complete)
4. **Verify** — `+"`remb projects list`"+` (confirm project appears with `+"`active`"+` status)

### 2. Update context after code changes

1. **Commit & push** — `+"`git add . && git commit -m \"feat: ...\" && git push`"+`
2. **Trigger scan** — `+"`remb push`"+` (detects new commits, runs cloud scan with progress)
3. **Wait for completion** — the CLI shows a progress bar; wait for `+"`Scan complete`"+` message

### 3. Save knowledge manually

1. **Save a feature** — `+"`remb save -f \"feature-name\" -c \"Description...\"`"+`
2. **Verify** — `+"`remb get -f \"feature-name\"`"+` (confirm entry was stored)

### 4. Load full context into AI session

1. **Bundle context** — `+"`remb context -o CONTEXT.md`"+`
2. **Feed to AI** — provide the generated `+"`CONTEXT.md`"+` file to your AI assistant

### 5. Analyze local changes before committing

1. **Make edits** — modify source files as needed
2. **Diff analysis** — `+"`remb diff --all`"+` (analyzes all staged + unstaged changes)
3. **Review** — check the generated context entries summarizing your changes

## MCP Integration

Add Remb as an MCP server in your IDE for direct AI tool access:

**Cursor / VS Code** (`+"`.cursor/mcp.json`"+` or `+"`.vscode/mcp.json`"+`):
`+"```"+`json
{
  "mcpServers": {
    "remb": {
      "command": "remb",
      "args": ["serve"]
    }
  }
}
`+"```"+`

Or connect to the hosted endpoint at `+"`%s/api/mcp`"+` for aggregated MCP access with all your connected servers.

## Exit Codes

- `+"`0`"+` — Success
- `+"`1`"+` — Error (auth failure, network error, validation error)

All commands respect the `+"`-p/--project <slug>`"+` flag or fall back to `+"`.remb.yml`"+` in the current directory tree.
`, slug, apiURL, apiURL)
}

func runInit(cmd *cobra.Command, args []string) {
	cwd, err := os.Getwd()
	if err != nil {
		output.Error(fmt.Sprintf("Cannot determine current directory: %v", err))
		os.Exit(1)
	}

	name := filepath.Base(cwd)
	if len(args) > 0 {
		name = args[0]
	}

	// Generate slug
	slug := strings.ToLower(name)
	slug = regexp.MustCompile(`[^a-z0-9]+`).ReplaceAllString(slug, "-")
	slug = strings.Trim(slug, "-")

	if slug == "" {
		output.Error("Invalid project name — must contain at least one alphanumeric character.")
		os.Exit(1)
	}

	// Check for existing config
	existing := config.FindProjectConfig(cwd)
	if existing != nil && !initForce {
		output.Warn(fmt.Sprintf("Already initialized at %s", output.Dim(existing.Dir+"/.remb.yml")))
		output.Info("Use " + output.Bold("--force") + " to overwrite.")
		return
	}

	// Determine IDE: flag > existing config > interactive prompt > all
	ide := resolveIDE(initIDE, func() string {
		if existing != nil {
			return existing.Config.IDE
		}
		return ""
	}())

	filePath, err := config.WriteProjectConfig(cwd, config.ProjectConfig{
		Project: slug,
		APIURL:  initAPIURL,
		IDE:     ide,
	})
	if err != nil {
		output.Error(fmt.Sprintf("Failed to write config: %v", err))
		os.Exit(1)
	}

	// Generate AI agent reference doc
	agentMdPath := filepath.Join(cwd, "REMB.md")
	if err := os.WriteFile(agentMdPath, []byte(generateAgentMd(slug, initAPIURL)), 0o644); err != nil {
		output.Warn(fmt.Sprintf("Could not write REMB.md: %v", err))
	}

	fmt.Println()
	output.Success(fmt.Sprintf("Project %s initialized!", output.Bold(slug)))
	output.KeyValue("Config", filePath)
	output.KeyValue("Agent docs", agentMdPath)
	output.KeyValue("Project", slug)
	output.KeyValue("API URL", initAPIURL)
	output.KeyValue("IDE", ide)
	fmt.Println()

	// Auto-register project on server if logged in
	apiKey := credentials.GetAPIKey()
	if apiKey != "" {
		// Auto-detect git info
		var repoURL, repoName, branch string
		if out, err := exec.Command("git", "-C", cwd, "remote", "get-url", "origin").Output(); err == nil {
			repoURL = strings.TrimSpace(string(out))
			re := regexp.MustCompile(`[/:]([-\w.]+/[-\w.]+?)(?:\.git)?$`)
			if m := re.FindStringSubmatch(repoURL); len(m) > 1 {
				repoName = m[1]
			}
		}
		if out, err := exec.Command("git", "-C", cwd, "rev-parse", "--abbrev-ref", "HEAD").Output(); err == nil {
			branch = strings.TrimSpace(string(out))
		}

		client, err := api.NewClient()
		if err == nil {
			_, err = client.CreateProject(api.CreateProjectRequest{
				Name:     slug,
				RepoURL:  repoURL,
				RepoName: repoName,
				Branch:   branch,
			})
			if err == nil {
				output.Success(fmt.Sprintf("Project registered on Remb %s", output.Dim("("+slug+")")))
			} else if apiErr, ok := err.(*api.APIError); ok && apiErr.StatusCode == 409 {
				output.Info(fmt.Sprintf("Project %s already exists on server — linked.", output.Bold(slug)))
			} else {
				output.Warn(fmt.Sprintf("Could not register project on server: %v", err))
				output.Info("You can register it later from the dashboard.")
			}
		}
	} else {
		output.Info("Run " + output.Bold("remb login") + " to register this project on the server.")
	}

	// Check for .gitignore
	gitignorePath := filepath.Join(cwd, ".gitignore")
	if _, err := os.Stat(gitignorePath); err == nil {
		output.Info(output.Dim("Tip:") + " .remb.yml and REMB.md are safe to commit — they contain no secrets.")
	}

	// Inject into IDE-specific instruction folders
	injected := injectIntoIDEContextFiles(cwd, slug, initAPIURL, ide)
	if len(injected) > 0 {
		output.Info("AI context injected into: " + output.Dim(strings.Join(injected, ", ")))
	}

	output.Info(output.Bold("REMB.md") + " generated — your IDE's AI agent can read it to learn all Remb commands.")
}

// ─── IDE Resolution ───────────────────────────────────────────────────────────

func resolveIDE(flagValue, configValue string) string {
	if flagValue != "" {
		normalized := strings.ToLower(flagValue)
		if isValidIDE(normalized) {
			return normalized
		}
		output.Warn(fmt.Sprintf(`Unknown IDE "%s". Using: all`, flagValue))
		return "all"
	}
	if configValue != "" && isValidIDE(configValue) {
		return configValue
	}
	// Interactive when connected to a real terminal
	if isTerminal() {
		return promptIDE()
	}
	return "all"
}

func isValidIDE(s string) bool {
	for _, ide := range validIDEs {
		if ide.value == s {
			return true
		}
	}
	return false
}

func promptIDE() string {
	fmt.Println()
	fmt.Println(output.Bold("  Which IDE are you using?"))
	fmt.Println()
	for i, ide := range validIDEs {
		fmt.Printf("    %s %s\n", output.Dim(fmt.Sprintf("%d.", i+1)), ide.label)
	}
	fmt.Println()
	fmt.Print(output.Bold("  Enter number: "))

	reader := bufio.NewReader(os.Stdin)
	line, _ := reader.ReadString('\n')
	line = strings.TrimSpace(line)

	for i, ide := range validIDEs {
		if line == fmt.Sprintf("%d", i+1) {
			fmt.Printf("%s\n", output.Dim(fmt.Sprintf("  Selected: %s", ide.label)))
			return ide.value
		}
	}
	fmt.Println(output.Dim("  No selection — using: all"))
	return "all"
}

func isTerminal() bool {
	fi, err := os.Stdout.Stat()
	if err != nil {
		return false
	}
	return (fi.Mode() & os.ModeCharDevice) != 0
}

func injectIntoIDEContextFiles(cwd, slug, apiURL, ide string) []string {
	const startMarker = "<!-- remb:start -->"
	const endMarker = "<!-- remb:end -->"

	all := ide == "all"
	is := func(name string) bool { return all || ide == name }

	type target struct {
		Path       string
		Label      string
		Content    string
		Enabled    bool
		FileHeader string // static content prepended before the remb block (e.g. YAML frontmatter)
	}

	targets := []target{
		{
			Path:    filepath.Join(cwd, ".github", "copilot-instructions.md"),
			Label:   ".github/copilot-instructions.md",
			Content: generateCopilotInstructions(slug, apiURL),
			Enabled: is("vscode"),
		},
		{
			Path:    filepath.Join(cwd, ".cursor", "rules", "remb.mdc"),
			Label:   ".cursor/rules/remb.mdc",
			Content: generateCursorRules(slug, apiURL),
			Enabled: is("cursor"),
		},
		{
			Path:    filepath.Join(cwd, ".windsurfrules"),
			Label:   ".windsurfrules",
			Content: generateWindsurfRules(slug, apiURL),
			Enabled: is("windsurf"),
		},
		{
			Path:    filepath.Join(cwd, ".clinerules"),
			Label:   ".clinerules",
			Content: generateClineRules(slug, apiURL),
			Enabled: is("cline"),
		},
		{
			Path:    filepath.Join(cwd, ".junie", "guidelines.md"),
			Label:   ".junie/guidelines.md",
			Content: generateJetBrainsPrompt(slug, apiURL),
			Enabled: is("jetbrains"),
		},
		{
			Path:    filepath.Join(cwd, "CLAUDE.md"),
			Label:   "CLAUDE.md",
			Content: generateClaudeMd(slug, apiURL),
			Enabled: is("claude"),
		},
		{
			Path:    filepath.Join(cwd, ".aider.conf.yml"),
			Label:   ".aider.conf.yml",
			Content: generateAiderConfig(slug, apiURL),
			Enabled: is("aider"),
		},
		{
			Path:       filepath.Join(cwd, ".github", "instructions", "remb-session.instructions.md"),
			Label:      ".github/instructions/remb-session.instructions.md",
			Content:    generateInstructionsMd(slug, apiURL),
			Enabled:    is("vscode"),
			FileHeader: "---\napplyTo: '**'\n---",
		},
	}

	var injected []string

	for _, t := range targets {
		if !t.Enabled {
			continue
		}

		dir := filepath.Dir(t.Path)
		if err := os.MkdirAll(dir, 0755); err != nil {
			continue
		}

		block := startMarker + "\n" + t.Content + "\n" + endMarker
		header := ""
		if t.FileHeader != "" {
			header = t.FileHeader + "\n\n"
		}

		existing, err := os.ReadFile(t.Path)
		if err == nil {
			text := string(existing)
			startIdx := strings.Index(text, startMarker)
			endIdx := strings.Index(text, endMarker)
			if startIdx != -1 && endIdx != -1 {
				// Markers found — surgically replace only the remb block
				updated := text[:startIdx] + block + text[endIdx+len(endMarker):]
				os.WriteFile(t.Path, []byte(updated), 0644)
			} else if t.FileHeader != "" {
				// File exists but unmanaged (no markers) — adopt it: write header + block
				os.WriteFile(t.Path, []byte(header+block+"\n"), 0644)
			} else {
				// Append block after existing content
				os.WriteFile(t.Path, []byte(strings.TrimRight(text, "\n")+"\n\n"+block+"\n"), 0644)
			}
		} else {
			os.WriteFile(t.Path, []byte(header+block+"\n"), 0644)
		}

		injected = append(injected, t.Label)
	}

	// Auto-generate MCP config files for IDEs that support it
	mcpConfig := "{\n  \"mcpServers\": {\n    \"remb\": {\n      \"command\": \"remb\",\n      \"args\": [\"serve\"]\n    }\n  }\n}\n"

	if is("vscode") {
		vscMcp := filepath.Join(cwd, ".vscode", "mcp.json")
		if !fileExists(vscMcp) {
			os.MkdirAll(filepath.Join(cwd, ".vscode"), 0755)
			if err := os.WriteFile(vscMcp, []byte(mcpConfig), 0644); err == nil {
				injected = append(injected, ".vscode/mcp.json")
			}
		}
	}

	if is("cursor") {
		cursorMcp := filepath.Join(cwd, ".cursor", "mcp.json")
		if !fileExists(cursorMcp) {
			os.MkdirAll(filepath.Join(cwd, ".cursor"), 0755)
			if err := os.WriteFile(cursorMcp, []byte(mcpConfig), 0644); err == nil {
				injected = append(injected, ".cursor/mcp.json")
			}
		}
	}

	return injected
}

func dirExists(path string) bool {
	info, err := os.Stat(path)
	return err == nil && info.IsDir()
}

func fileExists(path string) bool {
	info, err := os.Stat(path)
	return err == nil && !info.IsDir()
}

// ─── IDE-Specific Generators ─────────────────────────────────────────────────

func mcpToolReference() string {
	return `### Available MCP Tools

**Memory Management:**
- ` + "`remb__memory_list`" + ` — list memories (filter by tier, category, search)
- ` + "`remb__memory_search`" + ` — semantic search across all memories
- ` + "`remb__memory_load_context`" + ` — load all core + active memories as context
- ` + "`remb__memory_create`" + ` — create a new memory
- ` + "`remb__memory_update`" + ` — update an existing memory
- ` + "`remb__memory_delete`" + ` — delete a memory
- ` + "`remb__memory_promote`" + ` — promote a memory to a higher tier
- ` + "`remb__memory_stats`" + ` — get memory usage statistics
- ` + "`remb__memory_image_upload`" + ` — upload an image to memory
- ` + "`remb__memory_image_list`" + ` — list stored images

**Conversation Tracking:**
- ` + "`remb__conversation_log`" + ` — record what you discussed or accomplished
- ` + "`remb__conversation_history`" + ` — load recent conversation history

**Project & Context:**
- ` + "`remb__projects_list`" + ` — list all projects with feature counts
- ` + "`remb__project_get`" + ` — get project details, features, and latest scan
- ` + "`remb__context_save`" + ` — save a context entry for a feature
- ` + "`remb__context_get`" + ` — retrieve context entries (optional feature filter)
- ` + "`remb__context_bundle`" + ` — full project context as markdown

**Scanning & Analysis:**
- ` + "`remb__scan_trigger`" + ` — trigger a cloud scan
- ` + "`remb__scan_status`" + ` — check scan progress
- ` + "`remb__diff_analyze`" + ` — analyze a git diff and save extracted changes

**Cross-Project:**
- ` + "`remb__cross_project_search`" + ` — search across ALL projects for features, context, and memories
- ` + "`remb__context_bundle`" + ` — also works with other project slugs to load another project's full context
- ` + "`remb__memory_create`" + ` — create with no project_id to save global preferences that apply everywhere`
}

func generateCopilotInstructions(slug, apiURL string) string {
	return fmt.Sprintf(`# Remb — AI Context Management Rules

## Project: `+"`%s`"+`
## API: `+"`%s`"+`

## MANDATORY — Conversation Tracking

You MUST follow these rules in EVERY session:

1. **Session Start**: Call `+"`remb__conversation_history`"+` to load recent history and catch up on prior work.
2. **Load Context**: Call `+"`remb__memory_load_context`"+` to load all persistent project memories.
3. **During Work**: Call `+"`remb__conversation_log`"+` after completing significant work to record what was done.
4. **Session End**: Call `+"`remb__conversation_log`"+` with a summary before the conversation ends.
5. **Save Discoveries**: When you discover important architectural patterns, decisions, or gotchas, call `+"`remb__memory_create`"+` to save them.

These calls ensure context persists across sessions. Skipping them causes knowledge loss.

%s

## When to Use Each Tool

- **Starting a session** → `+"`conversation_history`"+` + `+"`memory_load_context`"+`
- **Need project info** → `+"`project_get`"+` or `+"`context_bundle`"+`
- **Saving knowledge** → `+"`context_save`"+` (feature-specific) or `+"`memory_create`"+` (cross-cutting)
- **After code changes** → `+"`scan_trigger`"+` to refresh, `+"`diff_analyze`"+` for targeted analysis
- **Finishing work** → `+"`conversation_log`"+` with summary of what was accomplished

## Cross-Project Referencing

When the user says "do it like I did in project X" or references another project:

1. Call `+"`remb__projects_list`"+` to find available projects
2. Call `+"`remb__cross_project_search`"+` with the concept to find matching patterns across all projects
3. Call `+"`remb__context_bundle`"+` with the other project's slug to load its full context
4. Apply the patterns from that project to the current work

**Global preferences** — memories created without a project_id apply to ALL projects. Use `+"`remb__memory_create`"+` with category "preference" and no project_id to save cross-project coding standards.`, slug, apiURL, mcpToolReference())
}

func generateCursorRules(slug, apiURL string) string {
	return fmt.Sprintf(`---
description: Remb context management — mandatory rules for AI sessions
globs: "**"
alwaysApply: true
---

# Remb — AI Context Management

**Project**: `+"`%s`"+` | **API**: `+"`%s`"+`

## MANDATORY Rules

1. At session start, call `+"`remb__conversation_history`"+` and `+"`remb__memory_load_context`"+`.
2. After completing significant work, call `+"`remb__conversation_log`"+` to record it.
3. Before ending the session, call `+"`remb__conversation_log`"+` with a final summary.
4. Save important discoveries with `+"`remb__memory_create`"+`.

%s

## Usage Patterns

| Situation | Tool |
|---|---|
| Starting a session | `+"`conversation_history`"+` + `+"`memory_load_context`"+` |
| Need project info | `+"`project_get`"+` or `+"`context_bundle`"+` |
| Saving knowledge | `+"`context_save`"+` or `+"`memory_create`"+` |
| After code changes | `+"`scan_trigger`"+` or `+"`diff_analyze`"+` |
| Finishing work | `+"`conversation_log`"+` |
| Reference another project | `+"`cross_project_search`"+` + `+"`context_bundle`"+` |`, slug, apiURL, mcpToolReference())
}

func generateWindsurfRules(slug, apiURL string) string {
	return fmt.Sprintf(`# Remb — AI Context Management

Project: %s | API: %s

## MANDATORY — Follow These Every Session

1. Session start → call `+"`remb__conversation_history`"+` and `+"`remb__memory_load_context`"+`
2. After significant work → call `+"`remb__conversation_log`"+`
3. Before ending → call `+"`remb__conversation_log`"+` with summary
4. Discoveries → call `+"`remb__memory_create`"+`

%s

## Quick Reference

- Starting: conversation_history + memory_load_context
- Project info: project_get or context_bundle
- Save knowledge: context_save (feature) or memory_create (general)
- After changes: scan_trigger or diff_analyze
- Finishing: conversation_log
- Reference another project: cross_project_search + context_bundle`, slug, apiURL, mcpToolReference())
}

func generateClineRules(slug, apiURL string) string {
	return fmt.Sprintf(`# Remb — AI Context Management

Project: %s | API: %s

## MANDATORY Rules

These rules MUST be followed in every session:

1. ALWAYS call `+"`remb__conversation_history`"+` at session start to load prior context.
2. ALWAYS call `+"`remb__memory_load_context`"+` at session start to load project memories.
3. ALWAYS call `+"`remb__conversation_log`"+` after completing significant work.
4. ALWAYS call `+"`remb__conversation_log`"+` before ending the session.
5. Save important patterns/decisions with `+"`remb__memory_create`"+`.

%s

## Cross-Project

When told "implement it like in project X", use `+"`cross_project_search`"+` to find patterns across projects, then `+"`context_bundle`"+` with the other project's slug.`, slug, apiURL, mcpToolReference())
}

func generateJetBrainsPrompt(slug, apiURL string) string {
	return fmt.Sprintf(`# Remb — AI Context Management

**Project**: `+"`%s`"+`
**API**: `+"`%s`"+`

## Mandatory Session Rules

1. At session start, call `+"`remb__conversation_history`"+` and `+"`remb__memory_load_context`"+`.
2. After completing significant work, call `+"`remb__conversation_log`"+`.
3. Before ending the session, call `+"`remb__conversation_log`"+` with a summary.
4. Save important discoveries with `+"`remb__memory_create`"+`.

%s

## Usage Guide

- **Starting a session**: Load history and context first
- **Need project info**: Use `+"`project_get`"+` or `+"`context_bundle`"+`
- **Saving knowledge**: `+"`context_save`"+` for features, `+"`memory_create`"+` for general patterns
- **After code changes**: `+"`scan_trigger`"+` to refresh, `+"`diff_analyze`"+` for targeted analysis
- **Finishing work**: Always log a summary with `+"`conversation_log`"+`
- **Referencing another project**: Use `+"`cross_project_search`"+` to find patterns, then `+"`context_bundle`"+` with that project's slug`, slug, apiURL, mcpToolReference())
}

func generateInstructionsMd(slug, apiURL string) string {
	return fmt.Sprintf(`# Remb — Mandatory Session Protocol

**Project**: `+"`%s`"+` | **API**: `+"`%s`"+`

## MANDATORY — Follow These in EVERY Session

### Session Start (do this FIRST, before anything else)
1. Call `+"`remb__conversation_history`"+` — load what was discussed and done in prior sessions
2. Call `+"`remb__memory_load_context`"+` — load all persistent project memories (core + active tier)

### During Work
3. Call `+"`remb__conversation_log`"+` after completing any significant task, bug fix, or feature
4. Call `+"`remb__memory_create`"+` when you discover important patterns, decisions, or gotchas worth keeping

### Session End (do this LAST, before the conversation ends)
5. Call `+"`remb__conversation_log`"+` with a summary: what was asked, what was done, key decisions made

Skipping these causes knowledge loss across sessions. The user expects you to follow this automatically.

---

%s

## When to Use What

| Situation | Tool |
|---|---|
| Starting a session | `+"`conversation_history`"+` + `+"`memory_load_context`"+` |
| Need project info | `+"`project_get`"+` or `+"`context_bundle`"+` |
| Saving knowledge | `+"`context_save`"+` (feature-specific) or `+"`memory_create`"+` (cross-cutting) |
| After code changes | `+"`scan_trigger`"+` or `+"`diff_analyze`"+` |
| Finishing work | `+"`conversation_log`"+` with summary |
| "Do it like in project X" | `+"`cross_project_search`"+` -> `+"`context_bundle`"+` with that project slug |
| Global coding preference | `+"`memory_create`"+` with no `+"`project_id`"+`, category "preference" |

## Memory Tiers

- **core** -- always loaded into every session automatically
- **active** -- loaded on-demand or when relevant to current query
- **archive** -- compressed long-term storage

Save architectural decisions and key patterns as `+"`core`"+` tier so they're always available.`, slug, apiURL, mcpToolReference())
}

func generateClaudeMd(slug, apiURL string) string {
	return fmt.Sprintf(`# Remb — AI Context Management

**Project**: `+"`%s`"+` | **API**: `+"`%s`"+`

## MANDATORY — Follow These in EVERY Session

### Session Start
1. Call `+"`remb__conversation_history`"+` — load prior session context
2. Call `+"`remb__memory_load_context`"+` — load all persistent project memories

### During Work
3. Call `+"`remb__conversation_log`"+` after completing any significant task
4. Call `+"`remb__memory_create`"+` when you discover important patterns or decisions

### Session End
5. Call `+"`remb__conversation_log`"+` with a final summary

%s

## Quick Reference

| Situation | Tool |
|---|---|
| Starting a session | `+"`conversation_history`"+` + `+"`memory_load_context`"+` |
| Need project info | `+"`project_get`"+` or `+"`context_bundle`"+` |
| Saving knowledge | `+"`context_save`"+` or `+"`memory_create`"+` |
| After code changes | `+"`scan_trigger`"+` or `+"`diff_analyze`"+` |
| Finishing work | `+"`conversation_log`"+` |
| Reference another project | `+"`cross_project_search`"+` + `+"`context_bundle`"+` |`, slug, apiURL, mcpToolReference())
}

func generateAiderConfig(slug, apiURL string) string {
	return fmt.Sprintf(`# Remb — AI Context Management

**Project**: `+"`%s`"+` | **API**: `+"`%s`"+`

## MANDATORY — Follow These in EVERY Session

### Session Start
1. Call `+"`remb__conversation_history`"+` — load prior session context
2. Call `+"`remb__memory_load_context`"+` — load all persistent project memories

### During Work
3. Call `+"`remb__conversation_log`"+` after completing any significant task
4. Call `+"`remb__memory_create`"+` when you discover important patterns or decisions

### Session End
5. Call `+"`remb__conversation_log`"+` with a final summary

%s

## Quick Reference

| Situation | Tool |
|---|---|
| Starting a session | `+"`conversation_history`"+` + `+"`memory_load_context`"+` |
| Need project info | `+"`project_get`"+` or `+"`context_bundle`"+` |
| Saving knowledge | `+"`context_save`"+` or `+"`memory_create`"+` |
| After code changes | `+"`scan_trigger`"+` or `+"`diff_analyze`"+` |
| Finishing work | `+"`conversation_log`"+` |
| Reference another project | `+"`cross_project_search`"+` + `+"`context_bundle`"+` |`, slug, apiURL, mcpToolReference())
}
