package config

import (
	"bufio"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

const ConfigFilename = ".remb.yml"
const DefaultAPIURL = "https://useremb.com"

type ProjectConfig struct {
	Project string
	APIURL  string
	IDE     string
}

type FoundConfig struct {
	Config ProjectConfig
	Dir    string
}

// FindProjectConfig walks up from cwd looking for .remb.yml.
func FindProjectConfig(cwd string) *FoundConfig {
	if cwd == "" {
		var err error
		cwd, err = os.Getwd()
		if err != nil {
			return nil
		}
	}

	dir, err := filepath.Abs(cwd)
	if err != nil {
		return nil
	}

	for {
		candidate := filepath.Join(dir, ConfigFilename)
		if _, err := os.Stat(candidate); err == nil {
			parsed := parseSimpleYAML(candidate)
			apiURL := parsed["api_url"]
			if apiURL == "" {
				apiURL = DefaultAPIURL
			}
			return &FoundConfig{
				Config: ProjectConfig{
					Project: parsed["project"],
					APIURL:  apiURL,
					IDE:     parsed["ide"],
				},
				Dir: dir,
			}
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			break
		}
		dir = parent
	}
	return nil
}

// WriteProjectConfig writes a .remb.yml in the given directory.
func WriteProjectConfig(dir string, cfg ProjectConfig) (string, error) {
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return "", fmt.Errorf("create directory: %w", err)
	}

	filePath := filepath.Join(dir, ConfigFilename)
	content := fmt.Sprintf(
		"# Remb project configuration\n# Generated by remb init\n\nproject: %s\napi_url: %s\n",
		cfg.Project, cfg.APIURL,
	)
	if cfg.IDE != "" {
		content += fmt.Sprintf("ide: %s\n", cfg.IDE)
	}

	if err := os.WriteFile(filePath, []byte(content), 0o644); err != nil {
		return "", fmt.Errorf("write config: %w", err)
	}
	return filePath, nil
}

func parseSimpleYAML(path string) map[string]string {
	result := make(map[string]string)

	f, err := os.Open(path)
	if err != nil {
		return result
	}
	defer f.Close()

	scanner := bufio.NewScanner(f)
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		idx := strings.Index(line, ":")
		if idx == -1 {
			continue
		}
		key := strings.TrimSpace(line[:idx])
		value := strings.TrimSpace(line[idx+1:])
		// Strip surrounding quotes
		if len(value) >= 2 {
			if (value[0] == '"' && value[len(value)-1] == '"') ||
				(value[0] == '\'' && value[len(value)-1] == '\'') {
				value = value[1 : len(value)-1]
			}
		}
		result[key] = value
	}
	return result
}
